# mutopia/J.S.Bach/Solo-Cello-Suites/Makefile

depth = ../../..

include $(depth)/make/Stepmake.make
include $(make-dir)/Mutopia.make

EXTRA_DIST_FILES=

examples=scsii-cello

include $(stepdir)/WWW.make
