depth = ../..

NAME= debian

# generic variables:
#
include ./$(depth)/make/Variables.make
include ./$(depth)/make/Files.make 
#

# generic targets and rules:
#
include ./$(depth)/make/Targets.make
include ./$(depth)/make/Rules.make
#


EXTRA_DISTFILES = README.debian.ex changelog control\
	copyright dirs diversions.ex docs examples info.ex menu.ex postinst\
	postrm rules watch
