# input/bugs/Makefile

depth = ../..

include $(depth)/make/Stepmake.make 
include $(make-dir)/Mutopia.make

examples= #beam-bug slur-bug  #why would we want to  demo Lily's errors?

include $(stepdir)/WWW.make

