# title	   makefile for test
# test/Makefile

depth = ..

NAME = lily-test
MODULE_NAME = lily-test

MODULE_CXXFLAGS = -I$(depth)/flower/include -I$(depth)/flower -I$(depth)/lily/include -I$(depth)/lily

include $(depth)/make/Stepmake.make
include $(stepdir)/C++.make

EXTRA_DIST_FILES = VERSION

# default: $(EXECUTABLE)

# include $(stepdir)/Executable.make

