# project  LilyPond -- the musical typesetter
# title	   makefile for test
# file	   test/Makefile 
#
# Copyright (c) 1997 by
#   	Jan Nieuwenhuizen <jan@digicash.com>
#	Han-Wen Nienhuys <hanwen@stack.nl>
#

# subdir level:
#
depth = ..
#

# generic variables:
#
include ./$(depth)/make/Variables.make 
#

# identify module:
#
NAME = test
MODULE_NAME = test

# descent order into subdirectories:
#
SUBDIRS =
#

include ./$(depth)/make/Files.make

# list of custom libraries:
#
CUSTOMLIBES = \

LOADLIBES +=
#

# main target of this module:
#
default: $(EXECUTABLE)
include ./$(depth)/make/Files.make 
include ./$(depth)/make/Targets.make
include ./$(depth)/make/Rules.make
#

EXECUTABLES=bow
include $(depth)/make/Executable.make


