# title	   makefile for test
# test/Makefile

depth = ..

NAME = lily-test
MODULE_NAME = lily-test

MODULE_CXXFLAGS = -I$(depth)/flower/include -I$(depth)/flower -I$(depth)/lily/include -I$(depth)/lily
MAKEFILES=C++

include $(depth)/make/Stepmake.make

# default: $(EXECUTABLE)

# include $(stepdir)/Executable.make

