# init/Makefile

depth = ..

INI_FILES = $(FLY_FILES) $(LY_FILES)
# DIST_FILES = Makefile $(INI_FILES)

INSTALLATION_DIR=$(datadir)/ly/
INSTALLATION_FILES=$(INI_FILES)

LOCALSTEPMAKE_TEMPLATES=mutopia

include $(depth)/make/stepmake.make 


include $(stepdir)/installfiles.make

