# init/Makefile

# subdir level:
#
depth = ..
#

build = ./$(depth)/lily/.build

# generic stuff/Makefile
#
include ./$(depth)/make/Stuff.make
#

# list of distribution files:
# 
INIFILES = $(shell ls *.ini)
DISTFILES = Makefile $(INIFILES)
#

