# init/Makefile

depth = ..

INI_FILES = $(FLY_FILES) $(LY_FILES)
# DIST_FILES = Makefile $(INI_FILES)

INSTALLATION_DIR=$(datadir)
INSTALLATION_FILES=$(INI_FILES)

LOCALMAKEFILES=Mutopia

include $(depth)/make/Stepmake.make 


include $(stepdir)/Installfiles.make

