# mutopia/J.S.Bach/Petites-Preludes/Makefile

depth = ../../..

EXTRA_DIST_FILES=

LILYINCLUDE:=$(LILYINCLUDE):out
export LILYINCLUDE

examples=preludes-2
LOCALSTEPMAKE_TEMPLATES=mutopia

mutopia-examples=preludes-score

include $(depth)/make/stepmake.make
