# mutopia/J.S.Bach/Petites-Preludes/Makefile

depth = ../../..

include $(depth)/make/Stepmake.make
include $(make-dir)/Mutopia.make

EXTRA_DIST_FILES=

examples=preludes-2

include $(stepdir)/WWW.make
