%%  Do not edit this file; it is auto-generated from LSR!
\version "2.11.23"

\header { texidoc = "
By default, bar numbers are printed only in the first measure.  This 
setting can be overridden, so that bar numbers appear on start of every
measure.


" }

\score{
    \relative c'{
	c1 c c
	\override Score.BarNumber 
	    #'break-visibility = #end-of-line-invisible
	\break
	c c c
    }
	\layout{ raggedright = ##t }
}



