# -*-python-*-

Import ('env')
sources = env['src_glob'] (env, '*.tex') + ['latin1.enc']
dir = env['DESTDIR'] + env['sharedir_package_version'] + '/tex'
env.Install (dir, sources)
env.Alias ('install', dir)
