depth = ..

### FIXME: change this back before merging with main!!!
SUBDIRS = regression tutorial mutopia manual lsr new 
#SUBDIRS = tutorial mutopia manual lsr new 

examples = typography-demo les-nereides wilhelmus proportional bach-schenker cary

LOCALSTEPMAKE_TEMPLATES=ly mutopia
EXTRA_DIST_FILES=paddy.abc

include $(depth)/make/stepmake.make
