# input/Makefile

# subdir level:
#
depth = ..
#

build = ./$(depth)/lily/$(outdir)/.build

# generic stuff/Makefile
#
include ./$(depth)/make/Stuff.make
#

# list of distribution files:
# 
LYFILES = $(shell ls *.ly)
TEXFILES = $(shell ls *.tex)
DISTFILES = Makefile $(LYFILES) $(TEXFILES)
#

