# -*-python-*-

Import ('env', 'install', 'src_glob')
sources = src_glob ('*.el') + ['lilypond-words.el']

e = env.Copy ()
a = '$PYTHON $srcdir/buildscripts/lilypond-words.py --el --dir=${TARGET.dir}'
e.Command ('lilypond-words.el',
	   ['#/lily/my-lily-lexer.cc',
	    '#/buildscripts/lilypond-words.py',
	    '#/scm/new-markup.scm',
	    '#/ly/engraver-init.ly',],
	   a)

install (sources, env['sharedir_package_version'] + '/elisp')
