# -*-python-*-

import os

Import ('env')
sources = env['src_glob'] (env, '*.el') + ['lilypond-words']
#gen_files = map (lambda x: os.path.splitext (x)[0], sources)
#gens = map (env.AT, sources)

e = env.Copy ()
a = '$PYTHON $srcdir/buildscripts/lilypond-words.py --el --dir=${TARGET.dir}'
e.Command ('lilypond-words.el', '#/lily/my-lily-lexer.cc', a)

dir = env['sharedir_package_version'] + '/elisp'
env.Install (dir, sources)
