ISOLANG = ja
depth = ../..
SUBDIRS = learning texidocs usage
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root
NO_PDF_FILES = 1

include $(depth)/make/stepmake.make
