ISOLANG = ja
depth = ../..
SUBDIRS = web learning texidocs usage included notation
STEPMAKE_TEMPLATES = documentation texinfo
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root
NO_PDF_FILES = 1

include $(depth)/make/stepmake.make
