depth = ..

# Hmm, name dir midi too, then?
NAME=midi


# compile fucks up on without autoconf -I flag.
STEPMAKE_TEMPLATES=c install # python-module

INSTALLATION_FILES=$(outdir)/midi.so
INSTALLATION_DIR=$(datadir)/python

# do nothing; module ins't used yet.

include $(depth)/make/stepmake.make

