depth = ..

# Hmm, name dir midi too, then?
NAME=midi

STEPMAKE_TEMPLATES=c install python-module

INSTALLATION_FILES=$(outdir)/midi.so
INSTALLATION_DIR=$(datadir)/python

include $(depth)/make/stepmake.make
