#!/bin/sh
def=`echo $1 | sed s/\\\./_/ | tr a-z A-Z`

cat << HERE
/*
  $1 -- part of LilyPond

  (c) 1997 $USERNAME <$MAILADRESS>
*/

HERE

if [ $1 != `basename .hh` ]
then
cat <<EOF
#ifndef $def
#define $def


#endif // $def
EOF
fi
