# flower/lib/include/Makefile

# subdir level:
#
depth = ../../..
#

# generic stuff/Makefile
#
include ./$(depth)/make/Include.make
#

# identify module:
#
MODULE_NAME = flower
include ./$(depth)/flower/.version
build = ./$(depth)/flower/$(outdir)/.build
#

