ISOLANG = hu
depth = ../..
SUBDIRS = web learning texidocs usage
STEPMAKE_TEMPLATES = documentation texinfo
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

EXTRA_DIST_FILES = web.texi

include $(depth)/make/stepmake.make
