# lib/include/Makefile

# subdir level:
#
depth = ../..
#

# identify module:
#
MODULE_NAME = lilypond
MAJOR_VERSION = $(TOPLEVEL_MAJOR_VERSION)
MINOR_VERSION = $(TOPLEVEL_MINOR_VERSION)
PATCH_LEVEL = $(TOPLEVEL_PATCH_LEVEL)
# use to send patches, always empty for released version:
MY_PATCH_LEVEL = $(TOPLEVEL_MY_PATCH_LEVEL)
build = ./$(depth)/lily/$(outdir)/.build
#

# generic stuff/Makefile
#
include ./$(depth)/make/Include.make
#

