%% DO NOT EDIT this file manually; it was automatically
%% generated from the LilyPond Snippet Repository
%% (http://lsr.di.unimi.it).
%%
%% Make any changes in the LSR itself, or in
%% `Documentation/snippets/new/`, then run
%% `scripts/auxiliar/makelsr.pl`.
%%
%% This file is in the public domain.

\version "2.23.13"

\header {
  lsrtags = "editorial-annotations, fretted-strings, really-simple"

  texidoc = "
Fingering instructions can be entered using a simple syntax.
"

  doctitle = "Adding fingerings to a score"
} % begin verbatim


\relative c'' {
  c4-1 d-2 f-4 e-3
}
