%% Do not edit this file; it is automatically
%% generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.13.10"

\header {
  lsrtags = "rhythms"

%% Translation of GIT committish: b2d4318d6c53df8469dfa4da09b27c15a374d0ca
  texidoces = "

Los números de compás se alinean de forma predeterminada por la
derecha con su objeto padre. Éste es por lo general el borde
izquierdo de una línea o, si los números se imprimen dentro de la
línea, el lado izquierdo de una línea divisoria.  Los números
también se pueden situar directamente sobre la barra de compás o
alineados por la izquierda con ella.

"

  doctitlees = "Alineación de los números de compás"

%% Translation of GIT committish: d96023d8792c8af202c7cb8508010c0d3648899d
  texidocde = "
Taktnummern sind standardmäßig links an ihrem Ursprungsobjet
ausgerichtet.  Das ist normalerweise die linke Ecke einer Linie oder,
wenn die Nummern innerhalb einer Zeile gesetzt werden, auf der
linken Seite eines Taktstrichs.  Die Nummern können auch
direkt über dem Taktstrich positioniert werden oder rechts vom
Taktstrich gesetzt werden.

"
  doctitlede = "Taktnummern ausrichten"


%% Translation of GIT committish: 21c8461ea87cd670a35a40b91d3ef20de03a0409
  texidocfr = "
Les numéros de mesure s'alignent en principe sur la droite de l'objet
dont ils dépendent.  C'est normalement le coin gauche de la portée ou,
en cours de ligne, à gauche de la barre.  Vous pouvez toutefois les
centrer par rapport à la barre ou les afficher à droite de la barre.

"
  doctitlefr = "Alignement des numéros de mesure"

  texidoc = "
Bar numbers by default are right-aligned to their parent object. This
is usually the left edge of a line or, if numbers are printed within a
line, the left hand side of a bar line.  The numbers may also be
positioned directly over the bar line or left-aligned to the bar line.

"
  doctitle = "Aligning bar numbers"
} % begin verbatim

\relative c' {
  \set Score.currentBarNumber = #111
  \override Score.BarNumber #'break-visibility = #'#(#t #t #t)
  % Increase the size of the bar number by 2
  \override Score.BarNumber #'font-size = #2
  % Print a bar number every second measure
  \set Score.barNumberVisibility = #(every-nth-bar-number-visible 2)
  c1 | c1
  % Center-align bar numbers
  \override Score.BarNumber #'self-alignment-X = #CENTER
  c1 | c1
  % Left-align bar numbers
  \override Score.BarNumber #'self-alignment-X = #LEFT
  c1 | c1
}

