%% DO NOT EDIT this file manually; it was automatically
%% generated from the LilyPond Wiki
%% (https://wiki.lilypond.community).
%%
%% Make any changes in the Wiki itself, or in
%% `Documentation/snippets/new/`, then run
%% `scripts/auxiliar/makelsr.pl`.
%%
%% This file is in the public domain.

\version "2.24.0"

\header {
  categories = "Rhythms, Tweaks and overrides"

  texidoc = "
If there are ten or fewer measures of rests, a series of longa and
breve rests (called in German @qq{Kirchenpausen} -- church rests) is
printed within the staff; otherwise a simple line is shown. This
default value of ten may be changed by overriding the
@code{expand-limit} property.
"

  doctitle = "Changing form of multi-measure rests"
} % begin verbatim


\relative c'' {
  \compressMMRests {
    R1*2 | R1*5 | R1*9
    \override MultiMeasureRest.expand-limit = 3
    R1*2 | R1*5 | R1*9
  }
}
