% DO NOT EDIT this file manually; it is automatically
% generated from Documentation/snippets/new
% Make any changes in Documentation/snippets/new/
% and then run scripts/auxiliar/makelsr.py
%
% This file is in the public domain.
%% Note: this file works from version 2.14.0
\version "2.14.0"

\header {
%% Translation of GIT committish: 6977ddc9a3b63ea810eaecb864269c7d847ccf98
  texidoces = "
Se puede hacer que los diagramas de posiciones se muestren sólo
cuando el acorde cambia o al comienzo de una nueva línea.

"

  doctitlees = "Cambios de acorde de posiciones de trastes"


%% Translation of GIT committish: 0a868be38a775ecb1ef935b079000cebbc64de40
texidocde = "
Bunddiagramme können definiert werden, sodass sie nur angezeigt werden,
wenn der Akkord sich ändert oder eine neue Zeile anfängt.

"

  doctitlede = "Akkordänderungen für Bunddiagramme"

%% Translation of GIT committish: 40bf2b38d674c43f38058494692d1a0993fad0bd
  texidocfr = "
Vous pouvez opter pour n'imprimer les diagrammes de fret qu'à l'occasion
d'un changement d'accord ou de saut de ligne.

"
  doctitlefr = "Changement d'accord et diagramme de fret"


  lsrtags = "fretted-strings"
  texidoc = "FretBoards can be set to display only when the chord changes
or at the beginning of a new line."
  doctitle = "chordChanges for FretBoards"
} % begin verbatim


\include "predefined-guitar-fretboards.ly"

myChords = \chordmode {
  c1 c1 \break
  \set chordChanges = ##t
  c1 c1 \break
  c1 c1 \break
}

<<
  \new ChordNames { \myChords }
  \new FretBoards { \myChords }
  \new Staff { \myChords }
>>
