%% DO NOT EDIT this file manually; it is automatically
%% generated from LSR http://lsr.di.unimi.it
%% Make any changes in LSR itself, or in Documentation/snippets/new/ ,
%% and then run scripts/auxiliar/makelsr.py
%%
%% This file is in the public domain.
\version "2.23.1"

\header {
  lsrtags = "expressive-marks"

  texidoc = "
An @emph{arpeggio} can be drawn across notes in different voices on the
same staff if the @code{Span_arpeggio_engraver} is added to the
@code{Staff} context:

"
  doctitle = "Creating arpeggios across notes in different voices"
} % begin verbatim

\new Staff \with {
  \consists "Span_arpeggio_engraver"
}
\relative c' {
  \set Staff.connectArpeggios = ##t
  <<
    { <e' g>4\arpeggio <d f> <d f>2 }
    \\
    { <d, f>2\arpeggio <g b>2 }
  >>
}
