%% DO NOT EDIT this file manually; it is automatically
%% generated from LSR http://lsr.dsi.unimi.it
%% Make any changes in LSR itself, or in Documentation/snippets/new/ ,
%% and then run scripts/auxiliar/makelsr.py
%%
%% This file is in the public domain.
\version "2.14.2"

\header {
%% Translation of GIT committish: 30339cb3706f6399c84607426988b25f79b4998c
  texidocfr = "
Les notes harmoniques artificielles, obtenues grâce à @code{\\harmonic},
ne sont pas pointées.  Ce comportement peut être modifié en activant la
propriété de contexte @code{harmonicDots}.

"
  doctitlefr = "Harmoniques pointées"

  lsrtags = "real-music, tweaks-and-overrides, unfretted-strings"

  texidoc = "
Artificial harmonics using @code{\\harmonic} do not show dots.  To
override this behavior, set the context property @code{harmonicDots}.

"
  doctitle = "Dotted harmonics"
} % begin verbatim


\relative c''' {
  \time 3/4
  \key f \major
  \set harmonicDots = ##t
  <bes f'\harmonic>2. ~
  <bes f'\harmonic>4. <a e'\harmonic>8( <gis dis'\harmonic> <g d'\harmonic>)
  <fis cis'\harmonic>2.
  <bes f'\harmonic>2.
}
