%% DO NOT EDIT this file manually; it is automatically
%% generated from LSR http://lsr.dsi.unimi.it
%% Make any changes in LSR itself, or in Documentation/snippets/new/ ,
%% and then run scripts/auxiliar/makelsr.py
%%
%% This file is in the public domain.
\version "2.14.2"

\header {
  lsrtags = "tweaks-and-overrides, keyboards"

%% Translation of GIT committish: 30339cb3706f6399c84607426988b25f79b4998c
  texidocfr = "
Les crochets d'indication de pédale peuvent se modifier de différentes
manières.

"
  doctitlefr = "Affinage des indications de pédale"

  texidoc = "
The appearance of pedal brackets may be altered in different ways.

"
  doctitle = "Fine-tuning pedal brackets"
} % begin verbatim


\paper { ragged-right = ##f }
\relative c'' {
  c2\sostenutoOn c
  c2\sostenutoOff c
  \once \override Staff.PianoPedalBracket #'shorten-pair = #'(-7 . -2)
  c2\sostenutoOn c
  c2\sostenutoOff c
  \once \override Staff.PianoPedalBracket #'edge-height = #'(0 . 3)
  c2\sostenutoOn c
  c2\sostenutoOff c
}
