%% DO NOT EDIT this file manually; it was automatically
%% generated from the LilyPond Wiki
%% (https://wiki.lilypond.community).
%%
%% Make any changes in the Wiki itself, or in
%% `Documentation/snippets/new/`, then run
%% `scripts/auxiliar/makelsr.pl`.
%%
%% This file is in the public domain.

\version "2.24.0"

\header {
  categories = "Staff notation, Workaround"

  texidoc = "
By default, metronome marks do not influence horizontal spacing. This
can be solved through a simple override, as shown in the second half of
the example.
"

  doctitle = "Forcing measure width to adapt to a metronome mark's width"
} % begin verbatim


example = {
  R1
  \tempo "Allegro molto" R1*6
  \tempo "poco rit." R1*2
  \tempo "a tempo" R1*8 \break
}

{
  \compressMMRests {
    \example
    \override Score.MetronomeMark.extra-spacing-width = #'(-3 . 0)
    \example
  }
}

\layout {
  ragged-right = ##t
}
