% DO NOT EDIT this file manually; it is automatically
% generated from Documentation/snippets/new
% Make any changes in Documentation/snippets/new/
% and then run scripts/auxiliar/makelsr.py
%
% This file is in the public domain.
%% Note: this file works from version 2.15.12
\version "2.15.12"

\header {
%% Translation of GIT committish: 8329db420f98f9d2f03ee8aec740b7ccf770b0d2
  texidocfr = "
Un glissando peut sauter un objet @code{NoteColumn}.

"
  doctitlefr = "Glissando par dessus un objet graphique"

  lsrtags = "expressive marks, staff-notation, tweaks-and-overrides"
  texidoc = "@code{NoteColumn} grobs can be skipped over by glissandi."
}

\relative c' {
  a2 \glissando
  \once \override NoteColumn #'glissando-skip = ##t
  f''4 d,
}
