% Do not edit this file; it is automatically
% generated from Documentation/snippets/new
% This file is in the public domain.
%% Note: this file works from version 2.13.4
\version "2.13.10"

\header {
  lsrtags = "staff-notation, fretted-strings"

  texidoc = "
Use a markup text to replace the (TAB) clef glyph with a modern font.

"
  doctitle = "Modern TAB text clef"
} % begin verbatim


\markup {
  This snippet is deprecated as of version 2.13.4 and will be removed
  in version 2.14.
}
