%% Do not edit this file; it is automatically
%% generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.13.10"

\header {
  lsrtags = "expressive-marks"

%% Translation of GIT committish: b2d4318d6c53df8469dfa4da09b27c15a374d0ca
  texidoces = "
Se pueden imprimir reguladores con un círculo en la punta
(notación «al niente») estableciendo la propiedad
@code{circled-tip} del objeto @code{Hairpin} al valor @code{#t}.

"
  doctitlees = "Impresión de reguladores utilizando la notación «al niente»"

%% Translation of GIT committish: d96023d8792c8af202c7cb8508010c0d3648899d
 texidocde = "
 Crescendo-Klammern können mit einem kleinen Kreis vor der Spitze
 notiert werden (al niente = bis zum Nichts), indem die
@code{circled-tip}-Eigenschaft des @code{Hairpin}-Objekts auf
@code{#t} gesetzt wird.

"
  doctitlede = "Crescendo Klammern al niente schreiben"
%% Translation of GIT committish: ae814f45737bd1bdaf65b413a4c37f70b84313b7
  texidocfr = "
Des crescendos ou decrescendos @emph{al niente} peuvent être indiqués de
manière graphique, en assignant @emph{vrai} (@code{#t}) à la
propriété @code{circled-tip}, ce qui affiche un cercle à leur extrémité.

"
  doctitlefr = "Impression de soufflets « al niente »"


  texidoc = "
Hairpins may be printed with a circled tip (al niente notation) by
setting the @code{circled-tip} property of the @code{Hairpin} object to
@code{#t}.

"
  doctitle = "Printing hairpins using al niente notation"
} % begin verbatim

\relative c'' {
  \override Hairpin #'circled-tip = ##t
  c2\< c\!
  c4\> c\< c2\!
}

