%% DO NOT EDIT this file manually; it was automatically
%% generated from the LilyPond Wiki
%% (https://wiki.lilypond.community).
%%
%% Make any changes in the Wiki itself, or in
%% `Documentation/snippets/new/`, then run
%% `scripts/auxiliar/makelsr.pl`.
%%
%% This file is in the public domain.

\version "2.24.0"

\header {
  categories = "Staff notation, Text, Vocal music"

  texidoc = "
Lyrics can be moved vertically to place them inside the staff. The
lyrics are moved with
@code{\\override LyricText.extra-offset = #'(0 . @var{dy})}, and
there are similar commands to move the extenders and hyphens. A good
value for @var{dy} must be found by trial and error.
"

  doctitle = "Putting lyrics inside the staff"
} % begin verbatim



<<
  \new Staff <<
    \new Voice = "voc" \relative c' { \stemDown a bes c8 b c4 }
  >>
  \new Lyrics \with {
    \override LyricText.extra-offset = #'(0 . 8.6)
    \override LyricExtender.extra-offset = #'(0 . 8.6)
    \override LyricHyphen.extra-offset = #'(0 . 8.6)
  } \lyricsto "voc" { La la -- la __ _ la }
>>
