%% DO NOT EDIT this file manually; it was automatically
%% generated from the LilyPond Wiki
%% (https://wiki.lilypond.community).
%%
%% Make any changes in the Wiki itself, or in
%% `Documentation/snippets/new/`, then run
%% `scripts/auxiliar/makelsr.pl`.
%%
%% This file is in the public domain.

\version "2.24.0"

\header {
  categories = "Headword"

  texidoc = "
Staff headword.
"

  doctitle = "Staff headword"
} % begin verbatim


\include "catalan.ly"

% Piotr Ilitch Tchaïkovski
% Le Lac des Cygnes, op. 20
% Danse Napolitaine
% arr. Laurence Sardain (Mutopia 2006/12/22)

#(set-global-staff-size 18)

trompette = \relative do'' {
  \clef treble
  \key mib \major
  \time 2/4

  <>\tweak staff-padding #1.5 ^\markup { \larger \italic Comodo } R2 |
  r8 \once \override TextScript.padding = #2.0
    sib16-.^\markup { \dynamic p \italic grazioso } do-.
    mib16( re)-. do-. sib-. |
  re8-. r8 re4->( |
  re8) do16-. re-. mib( re) do-. re-. |
  do8-. r8 sib4-> |
}

tambourin = \drummode {
  \time 2/4
  r8 tamb16 16 8 8 |
  r8 16 16 8 8 |
  r8 8 r8 8 |
  r8 16 16 8 8 |
  r8 8 r8 8 |
}

upper = \relative do' {
  \clef treble
  \key mib \major
  \time 2/4

  r8\p <sol sib mib>16-. q-. q8-. q-. |
  r8 <sol sib mib>16-. q-. q8-. q-. |
  r8 <lab sib re>16-. q-. q8-. q-. |
  r8 <lab sib re>16-. q-. q8-. q-. |
  r8 <sol sib mib>16-. q-. q8-. q-. |
}

lower = \relative do {
  \clef bass
  \key mib \major
  \time 2/4

  mib4-. r4 |
  sib-. r |
  fa'-. r |
  sib,-. r |
  mib4-. r4 |
}

\score {
  <<
    \context Staff = "trumpet" \with {
      instrumentName = \markup {
        "Trumpet" \concat { B \teeny \raise #0.4 \flat } }
    } \transpose sib do' \trompette
    \context RhythmicStaff = "tambourin" \with {
      instrumentName = "Tambourine"
    } \tambourin
    \context PianoStaff = "prima" \with {
      instrumentName = "Piano"
    } <<
        \context Staff = "uppera" \upper
        \context Staff = "lowera" \lower
      >>
  >>
  \layout { indent = 2.5\cm }
}

\score {
  <<
    \context Staff = "trumpet" \with { midiInstrument = "trumpet" }
      \trompette
    \context DrumStaff = "tambourin"
      \tambourin
    \context Staff = "piano"
      <<
        \upper
        \lower
      >>
  >>
  \midi { \tempo 4 = 72 }
}
