%% DO NOT EDIT this file manually; it is automatically
%% generated from LSR http://lsr.dsi.unimi.it
%% Make any changes in LSR itself, or in Documentation/snippets/new/ ,
%% and then run scripts/auxiliar/makelsr.py
%%
%% This file is in the public domain.
\version "2.14.2"

\header {
  lsrtags = "fretted-strings"

%% Translation of GIT committish: b482c3e5b56c3841a88d957e0ca12964bd3e64fa
  texidoces = "
La dirección de las plicas se contola de la misma forma en la
tablatura que en la notación tradicional. Las barras se pueden
poner horizontales, como se muestra en este ejemplo.

"
  doctitlees = "Comportamiento de las plicas y las barras de corchea en tablaturas"


%% Translation of GIT committish: 0a868be38a775ecb1ef935b079000cebbc64de40
  texidocde = "
Die Richtung von Hälsen wird in Tabulaturen genauso wie in normaler Notation
eingestellt.  Balken können horizontal eingestellt werden, wie das Beispiel
zeigt.

"
  doctitlede = "Hals- und Balkenverhalten in einer Tabulatur"

%% Translation of GIT committish: 28097cf54698db364afeb75658e4c8e0e0ccd716
  texidocfr = "
La direction des hampes se gère dans les tablatures tout comme en
notation traditionnelle.  Les ligatures peuvent être mises à l'horizontale
comme le montre cet exemple.

"
  doctitlefr = "Hampes et ligatures en mode tablature"

  texidoc = "
The direction of stems is controlled the same way in tablature as in
traditional notation. Beams can be made horizontal, as shown in this
example.

"
  doctitle = "Stem and beam behavior in tablature"
} % begin verbatim


\new TabStaff {
  \relative c {
    \tabFullNotation
    g16 b d g b d g b
    \stemDown
    \override Beam #'concaveness = #10000
    g,,16 b d g b d g b
  }
}
