% DO NOT EDIT this file manually; it is automatically
% generated from Documentation/snippets/new
% Make any changes in Documentation/snippets/new/
% and then run scripts/auxiliar/makelsr.py
%
% This file is in the public domain.
%% Note: this file works from version 2.15.15
\version "2.15.15"

\header {
%% Translation of GIT committish: 2d548a99cb9dba80f2ff035582009477cd37eceb
  texidoces = "

Se pueden imprimir estilos alternativos del corchete o gancho de las
corcheas y figuras menores, mediante la sobreescritura de la propiedad
@code{flag} del objeto @code{Stem}.  Son valores válidos
@code{modern-straight-flag} y @code{old-straight-flag}.

"
  doctitlees = "Uso de estilos alternativos para los corchetes"



  lsrtags = "rhythms, tweaks-and-overrides"

  texidoc = "
Alternative styles of flag on eighth and shorter notes can be displayed
by overriding the @code{stencil} property of @code{Flag}.  Valid values
are @code{modern-straight-flag} and @code{old-straight-flag}.

"
  doctitle = "Using alternative flag styles"
} % begin verbatim


testnotes = {
  \autoBeamOff
  c8 d16 c32 d64 \acciaccatura { c8 } d64 r4
}

\relative c' {
  \time 2/4
  \testnotes

  \override Flag #'stencil = #modern-straight-flag
  \testnotes

  \override Flag #'stencil = #old-straight-flag
  \testnotes

  \revert Flag #'stencil
  \testnotes
}

