%% DO NOT EDIT this file manually; it is automatically
%% generated from LSR http://lsr.di.unimi.it
%% Make any changes in LSR itself, or in Documentation/snippets/new/ ,
%% and then run scripts/auxiliar/makelsr.py
%%
%% This file is in the public domain.
\version "2.23.9"

\header {
  lsrtags = "ancient-notation, expressive-marks"

  texidoc = "
This short vertical line placed above the note is commonly used in
baroque music.  Its meaning can vary, but generally indicates notes
that should be played with more @qq{weight}.  The following example
demonstrates how to achieve such a notation.

"
  doctitle = "Vertical line as a baroque articulation mark"
} % begin verbatim

upline =
\tweak stencil
  #(lambda (grob)
    (grob-interpret-markup grob #{ \markup \draw-line #'(0 . 1) #}))
  \stopped

\relative c' {
  a'4^\upline a( c d')_\upline
}
