%% Do not edit this file; it is automatically
%% generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.13.16"

\header {
  lsrtags = "repeats, staff-notation, chords"

%% Translation of GIT committish: 00ef2ac3dd16e21c9ffdffaa4d6d043a3f1a76e6
  texidoces = "
Mediante la adición del grabador @code{Volta_engraver} al
pentagrama pertinente, se pueden poner los corchetes de primera y
segunda vez debajo de los acordes.

"
  doctitlees = "Corchetes de primera y segunda vez debajo de los acordes"



%% Translation of GIT committish: d96023d8792c8af202c7cb8508010c0d3648899d
  texidocde = "
Indem man den @code{Volta_engraver} zu dem entsprechenden Notensystem
hinzufügt, können Wiederholungsklammern unterhalb der Akkorde gesetzt
werden.

"
  doctitlede = "Wiederholungs-(Volta-)Klammern unterhalb der Akkordsymbole"

  texidoc = "
By adding the @code{Volta_engraver} to the relevant staff, volte can be
put under chords.

"
  doctitle = "Volta below chords"
} % begin verbatim

\score {
  <<
    \chords {
      c1
      c1
    }
    \new Staff \with {
      \consists "Volta_engraver"
    }
    {
      \repeat volta 2 { c'1 }
      \alternative { c' }
    }
  >>
  \layout {
    \context {
      \Score
      \remove "Volta_engraver"
    }
  }
}
