# mutopia/Makefile

depth = ../..

# do Coriolan if you have plenty RAM / CPU
examples=coriolan oboi-part viola-part
# examples= oboi-part viola-part

LOCALSTEPMAKE_TEMPLATES=mutopia

include $(depth)/make/stepmake.make

