ISOLANG = it
depth = ../..
SUBDIRS = learning texidocs web usage
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

EXTRA_DIST_FILES = web.texi

include $(depth)/make/stepmake.make
