ISOLANG = it
depth = ../..
SUBDIRS = learning texidocs web usage included notation
STEPMAKE_TEMPLATES = documentation texinfo
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

include $(depth)/make/stepmake.make
