depth = ../../../..

STEPMAKE_TEMPLATES=
LOCALSTEPMAKE_TEMPLATES=

include $(depth)/make/stepmake.make

EXTRA_DIST_FILES += $(call src-wildcard,*.ly)
EXTRA_DIST_FILES += $(call src-wildcard,*.ily)
EXTRA_DIST_FILES += $(call src-wildcard,*.tely)
EXTRA_DIST_FILES += $(call src-wildcard,*.itely)
