# -*-python-*-

Import ('env')
sources = env['src_glob'] (env, '*.vim') + ['lilypond-words.vim']

e = env.Copy ()
a = '$PYTHON $srcdir/buildscripts/lilypond-words.py --words --vim --dir=${TARGET.dir}'
e.Command ('lilypond-words.vim',
	   ['#/lily/my-lily-lexer.cc',
	    '#/buildscripts/lilypond-words.py',
	    '#/scm/new-markup.scm',
	    '#/ly/engraver-init.ly',],
	   a)

dir = env['sharedir_package_version'] + '/vim'
env.Install (dir, sources)
