# -*-python-*-

Import ('env', 'install', 'src_glob')
sources = src_glob ('*.vim') + ['lilypond-words.vim']

e = env.Copy ()
a = '$PYTHON $srcdir/buildscripts/lilypond-words.py --words --vim --dir=${TARGET.dir}'
e.Command ('lilypond-words.vim',
	   ['#/lily/lily-lexer.cc',
	    '#/buildscripts/lilypond-words.py',
	    '#/scm/markup.scm',
	    '#/ly/engraver-init.ly',],
	   a)

install (sources, env['sharedir_package_version'] + '/vim')
