ISOLANG = cs
depth = ../..
# SUBDIRS = web learning notation texidocs usage included essay extending
SUBDIRS = web learning texidocs essay usage
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root
NO_PDF_FILES = 1
EXTRA_DIST_FILES = web.texi

include $(depth)/make/stepmake.make
