\input texinfo @c -*-texinfo-*-
@setfilename installing.info
@settitle LilyPond on Windows

@html
<!--- @@WEB-TITLE@@=Windows Installation --->
@end html

@node Top
@top

@chapter WINDOWS - Installing GNU LilyPond on Windows

This document explains how to install the binary release for windows
on a Microsoft Windows 95, 98, ME, NT, 2000 or XP machine.  Please
follow the instructions carefully.  If it doesn't work for you, please
send a bugreport, following the guidelines in the section on
bugreports below.


@section Windows binary setup 

If you run Windows NT, 2000 or XP, please become administrator first
(currently, installing as an ordinary user will not work).  Download and
run @uref{http://www.lilypond.org/gnu-windows/setup.exe, setup.exe}.
You will be asked some questions. If you are unsure just click "Next".
Do not change the default install directory @file{c:/cygwin}.

This installs LilyPond, and Cygwin, GUILE, Python, teTeX (MikTeX is not
supported).  If you already have some of that software under
@file{c:/cygwin}, then don't worry: nothing will be installed twice.

If you want to install any of this software by hand, do this
@strong{before} you run @file{setup.exe}, otherwise your LilyPond setup
may not work.


@subsection Additional software

If you install the Cygwin's XFree86 X11 window system, tetex-x11 and
ghostscript-x11 packages too, you can view the @code{dvi} output doing
@code{xdvi test.dvi}.

LilyPond needs a PostScript/PDF viewer to be really useful.  At this
time (Sun Aug 11 2002), such software is not available in Cygwin, so
you must use native Windows software instead.

@table @samp
@item Ghostview.

You can use GSView-2.6.  This old package has two advantages.  It has
gsview and ghostscript bundeled, and it doesn't popup @emph{Register
Now|Cancel} windows all the time.

Click @uref{ftp://ftp.cs.wisc.edu/ghost/ghostgum/gsv26w32.exe,here} to
install GSView-2.6 (GhostView for Windows), or visit
@uref{ftp://ftp.cs.wisc.edu/ghost/ghostgum,ftp.cs.wisc.edu}.

@c check/update versions
You can also use the newer versions GSView-3.6 and GhostScript-6.50,
which can also display PDFs.  You get annoying @emph{Register
Now|Cancel} popups, though.

Click @uref{ftp://ftp.cs.wisc.edu/ghost/ghostgum/gsv36w32.exe,here} for
GSview and 
Click @uref{ftp://mirror.cs.wisc.edu/pub/mirrors/ghost/AFPL/gs650/gs650w32.exe
,here} for GhostScript.
@uref{ftp://ftp.cs.wisc.edu/ghost/ghostgum,ftp.cs.wisc.edu}.
or visit the
@uref{http://www.cs.wisc.edu/~ghost/,Ghostscript, Ghostview and GSview site}.
@end table


@section Testing LilyPond

Open a LilyPond shell (To open a a lilypond shell, click the "GNU
LilyPond" or "Cygwin" icon), and type

@quotation
@example
lilypond --help
@end example
@end quotation

You should see something similar to

@quotation
@example
Usage: lilypond [OPTION]... [FILE]...

Typeset music and or play MIDI from FILE

LilyPond is a music typesetter.  It produces beautiful sheet music
using a high level description file as input.  LilyPond is part of 
the GNU Project.

Options:
  -h,--help             this help
[..]
@end example
@end quotation

Then, prepare a file called @file{foo.ly}, by issuing
@quotation
@example
notepad foo.ly
@end example
@end quotation
Enter the following into the file
@quotation
@example

\score @{ \notes @{ c4 ( ) c4 @} @}

@end example
@end quotation
Close the file and save it. Run the following command. It should say
@code{PS output to `foo.ps', DVI output to `foo.dvi'}.
@quotation
@example

ly2dvi -P foo

@end example
@end quotation
If you install the Cygwin's XFree86 X11 window system, tetex-x11 and
ghostscript-x11 packages too, you can view the @code{dvi} output doing
@code{xdvi test.dvi}.  If you have installed a PostScript/PDF viewer,
such as @code{GSView} from @uref{http://www.cs.wisc.edu/~ghost},
viewing the PS file can be done with:
@quotation
@example

gsview32 foo.ps

@end example
@end quotation

If this works, then you can head to the
@uref{../../user/out-www/lilypond/Tutorial.html,Tutorial} to start using
LilyPond.



@section Removing LilyPond

Start @file{setup.exe}, click Next, select "Install from Local
Directory". Then click next until you reach "Select packages to
install". Click "View". Now, for every package, click on the recycle
icon until it says "Uninstall". Then, click Next.

(If you find this too tedious, you can also simply remove
@file{c:/cygwin}. This also removes the @file{/home/} directories under
cygwin (i.e. @file{C:\CYGWIN\HOME}, so make sure that you bring
important files in safety first.)

@section Troubleshooting

For problems and solutions see
@uref{http://lilypond.org/wiki?TroubleshootingWindows,Troubleshooting
Windows}


@section Bugreports

We can only help you with a problem if you give a full, detailed
bugreport. A bugreport includes

@itemize @bullet
@item A @emph{precise} description of the problem.  
@item A full description of your platform (machine type, operating
system)
@item All version numbers of relevant software you run.  Specifically, we
want to see the output of the  following commands: 
@quotation
@example
  python --version
  lilypond --version
  ly2dvi --version
@end example
@end quotation
@item If ly2dvi fails, then please run it as follows and include the
  output in the 
@quotation
@example
  ly2dvi --verbose MY-FILE
@end example
@end quotation
@end itemize

You can also check out
@uref{http://lilypond.org/wiki/?TroubleshootingWindows} for more
instructions on how to make a bug report.


@ignore

[TODO:


* emacs-mode installation, figure out and describe proper
emacs-on-cygwin setup.
]


Let's take this step by step.

It should not be critical which MikTeX version you use.
Let's first verify that your MikTeX works as it should.
Open a DOS window. Run the commands
>> latex sample2e
 Should produce some lines of output
>> yap sample2e
 Should display a three page document.

Next step; verify that the geometry package is in place. 
Save the attached file to the directory where you run 
your DOS window. Run the commands
>> latex geometrytest
>> yap geometrytest
This one you should get a single page document with some text
in each corner.
]

@end ignore
