\score{
	<
	\context Staff \notes{ 
	  \skip 4*27;
	  \skip 4*27;
	  \skip 4*27;
	  \skip 4*27;
	  }
	\context Lyrics \lyrics{ 
aaaaaaaaaaaaaaaaaaa
xxx\break
bbbbbbbbbbbbbbbbbbb
xxx\break
ccccccccccccccccccc
xxx\break
ddddddddddddddddddd
xxx\break
eeeeeeeeeeeeeeeeeee
xxx\break
fffffffffffffffffff
xxx\break
ggggggggggggggggggg
xxx\break
hhhhhhhhhhhhhhhhhhh
xxx\break
iiiiiiiiiiiiiiiiiii
xxx\break
jjjjjjjjjjjjjjjjjjj
xxx\break
kkkkkkkkkkkkkkkkkkk
xxx\break
lllllllllllllllllll
xxx\break
mmmmmmmmmmmmmmmmmmm
xxx\break
nnnnnnnnnnnnnnnnnnn
xxx\break
ooooooooooooooooooo
xxx\break
ppppppppppppppppppp
xxx\break
qqqqqqqqqqqqqqqqqqq
xxx\break
rrrrrrrrrrrrrrrrrrr
xxx\break
sssssssssssssssssss
xxx\break
ttttttttttttttttttt
xxx\break
uuuuuuuuuuuuuuuuuuu
xxx\break
vvvvvvvvvvvvvvvvvvv
xxx\break
wwwwwwwwwwwwwwwwwww
xxx\break
xxxxxxxxxxxxxxxxxxx
xxx\break
yyyyyyyyyyyyyyyyyyy
xxx\break
zzzzzzzzzzzzzzzzzzz
xxx\break
...................
xxx\break
AAAAAAAAAAAAAAAAAAA
xxx\break
BBBBBBBBBBBBBBBBBBB
xxx\break
CCCCCCCCCCCCCCCCCCC
xxx\break
DDDDDDDDDDDDDDDDDDD
xxx\break
EEEEEEEEEEEEEEEEEEE
xxx\break
FFFFFFFFFFFFFFFFFFF
xxx\break
GGGGGGGGGGGGGGGGGGG
xxx\break
HHHHHHHHHHHHHHHHHHH
xxx\break
IIIIIIIIIIIIIIIIIII
xxx\break
JJJJJJJJJJJJJJJJJJJ
xxx\break
KKKKKKKKKKKKKKKKKKK
xxx\break
LLLLLLLLLLLLLLLLLLL
xxx\break
MMMMMMMMMMMMMMMMMMM
xxx\break
NNNNNNNNNNNNNNNNNNN
xxx\break
OOOOOOOOOOOOOOOOOOO
xxx\break
PPPPPPPPPPPPPPPPPPP
xxx\break
QQQQQQQQQQQQQQQQQQQ
xxx\break
RRRRRRRRRRRRRRRRRRR
xxx\break
SSSSSSSSSSSSSSSSSSS
xxx\break
TTTTTTTTTTTTTTTTTTT
xxx\break
UUUUUUUUUUUUUUUUUUU
xxx\break
VVVVVVVVVVVVVVVVVVV
xxx\break
WWWWWWWWWWWWWWWWWWW
xxx\break
XXXXXXXXXXXXXXXXXXX
xxx\break
YYYYYYYYYYYYYYYYYYY
xxx\break
ZZZZZZZZZZZZZZZZZZZ
xxx\break
	}
	>
	\paper {
               castingalgorithm = \Wordwrap;
	       linewidth = 40.\mm;
	}
}

\version "1.0.16"; 
