# input/test/Makefile

depth = ../..
examples=font20 mark knee beam-interstaff slur-interstaff denneboom sleur repeat hara-kiri  grace
LOCALSTEPMAKE_TEMPLATES=mutopia

include $(depth)/make/stepmake.make 

