# mutopia/Makefile

depth = ..

SUBDIRS = J.S.Bach Coriolan W.A.Mozart F.Schubert D.Zipoli Hymns D.Scarlatti L.Mozart E.Satie N.W.Gade

examples= 
LOCALSTEPMAKE_TEMPLATES=mutopia

include $(depth)/make/stepmake.make

EXTRA_DIST_FILES +=  



