# mutopia/Makefile

depth = ..

SUBDIRS = J.S.Bach Coriolan W.A.Mozart F.Schubert D.Zipoli Hymns D.Scarlatti L.Mozart E.Satie

examples= gallina
LOCALSTEPMAKE_TEMPLATES=mutopia

include $(depth)/make/stepmake.make

EXTRA_DIST_FILES +=  TODO



