# mutopia/Makefile

depth = ..

SUBDIRS = J.S.Bach Coriolan F.Schubert D.Zipoli Hymns L.Mozart E.Satie N.W.Gade

examples= 
LOCALSTEPMAKE_TEMPLATES=mutopia

include $(depth)/make/stepmake.make

EXTRA_DIST_FILES +=  



