# mutopia/Makefile

# subdir level:
#
depth = ..
#

# descent order into subdirectories:
#
SUBDIRS = J.S.Bach Coriolan W.A.Mozart
EXTRA_DISTFILES +=  TODO

examples=standchen gallina


#
# generic stuff/Makefile
#
include $(depth)/make/Mutopia.make

include $(depth)/make/WWW.make
