# mutopia/Makefile

# subdir level:
#
depth = ..
#

# descent order into subdirectories:
#
SUBDIRS = J.S.Bach Coriolan
EXTRA_DISTFILES +=  TODO
#
# generic stuff/Makefile
#
include ./$(depth)/make/Mutopia.make
