# Documentation/topdocs/Makefile

depth = ../..

SUBDIRS=
BLURBS=BLURB #COPERTINA FLAPTEKST
AT_FILES = $(BLURBS) # 
at-dir = $(doc-dir)/
at-ext = .in
BLURBS=BLURB COPERTINA FLAPTEKST

STEPMAKE_TEMPLATES=documentation yolily-topdoc

include $(depth)/make/stepmake.make 

