\input texinfo @c -*- coding: utf-8; mode: texinfo; -*-
@ignore
    Translation of GIT committish: FILL-IN-HEAD-COMMITTISH

    When revising a translation, copy the HEAD committish of the
    version that you are working on.  See TRANSLATION for details.
@end ignore
@setfilename contrib-guide.info
@settitle GNU LilyPond Contributor's Guide
@documentencoding UTF-8
@documentlanguage en

@include macros.itexi

@afourpaper

@ifnottex
@node Top
@top GNU LilyPond --- Contributor's Guide
@chapheading The music typesetter
@end ifnottex


@ifhtml
@ifclear bigpage
This document is also available as a
@uref{source/Documentation/devel/contrib-guide.pdf,PDF} and as
@c FIXME: update @uref{} stuff.
@uref{source/Documentation/devel/,one big page}.
@end ifclear
@ifset bigpage
This document is also available as a
@uref{source/Documentation/devel/contrib-guide.pdf,PDF} and as a
@uref{source/Documentation/devel/contrib-guide/index.html,HTML indexed multiple pages}.
@end ifset
@end ifhtml


@iftex
@exampleindent 0
@finalout

@titlepage
@title LilyPond
@subtitle The music typesetter
@titlefont{Contributor's Guide}
@author The LilyPond development team

Copyright @copyright{} 1999--2008 by the authors

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1
or any later version published by the Free Software Foundation;
with no Invariant Sections.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.
@end quotation

@vskip 20pt

For LilyPond version
@end titlepage
@end iftex

@copying
Copyright @copyright{} 1999--2008 by the authors

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1
or any later version published by the Free Software Foundation;
with no Invariant Sections.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.
@end quotation
@end copying

@ifnottex
This file documents contributing to GNU LilyPond.

Copyright 1999--2008 by the authors

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1
or any later version published by the Free Software Foundation;
with no Invariant Sections.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.
@end quotation
@end ifnottex

@ifnottex

More information can be found at
@uref{http://@/www@/.lilypond@/.org/}.  The website contains
on-line copies of this and other documentation.

@menu
* Starting with git::
* Compiling from source::
* Documentation work::
* Website work::
* LSR work::
* Issues::
* Programming work::
* Release work::
@end menu
@end ifnottex

@contents

@include git-starting.itexi
@include compiling.itexi
@include doc-work.itexi
@include website-work.itexi
@include lsr-work.itexi
@include issues.itexi
@include programming-work.itexi
@include release-work.itexi

@bye

