ISOLANG = fr
depth = ../..
SUBDIRS = application learning notation texidocs
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

include $(depth)/make/stepmake.make
