\input texinfo @c -*- coding: utf-8; mode: texinfo; documentlanguage: fr -*-
@ignore
    Translation of GIT committish: 196dca281894cb360f1691cdb76faf5bf53d7724

    When revising a translation, copy the HEAD committish of the
    version that you are working on.  For details, see the Contributors'
    Guide, node Updating translation committishes..
@end ignore

@setfilename web.info
@settitle LilyPond -- la notation musicale pour tous
@documentencoding UTF-8
@documentlanguage fr
@afourpaper

@set FDL
@set web
@include fr/macros.itexi
@include weblinks.itexi


@c Translators: John Mandereau
@c Translators checkers: Jean-Charles Malahieude

@c `Web' was born 2003-03-30 with this commit:
@c Initial revision
@c author: Han-Wen Nienhuys
@c commit: d189a2119004c2f75da2020ea2ed36d817582fc5

@c @macro copyrightDeclare
@c Copyright @copyright{} 2003--2022 par les auteurs.
@c @end macro

@copying
Copyright @copyright{} 2009--2022 par les auteurs.

@c next line is necessary for broken pre-4.13 texinfo's
@c install-info, so leave it there until we officially
@c bump the required version.  -gp
This file documents the LilyPond website.

@quotation
Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free Documentation License,
Version 1.1 or any later version published by the Free Software
Foundation; with no Invariant Sections.  A copy of the license is
included in the section entitled ``GNU Free Documentation
License''.
@end quotation
@end copying

@c Info files are no longer installed in a subdirectory, images are
@c expected to be found in lilypond/ subdirectory.
@dircategory GNU LilyPond -- le typographe de musique
@direntry
* LilyPond Website: (lilypond-web).        Prévisualisation du site.
@end direntry


@c TITLE PAGE
@ifnottex
@node Top
@c This is intentionally blank because we have @settitle above
@top
@end ifnottex


@c hack for texi2html, bleh -gp
@ifnothtml

@finalout

@titlepage
@title LilyPond
@subtitle Le système de notation musicale
@titlefont{Informations générales}
@author Équipe de développement de LilyPond

@vskip 0pt plus 1filll
@c @vskip 20pt

@insertcopying

Pour LilyPond version @version{}
@end titlepage
@end ifnothtml
@c end hack for texi2html

@c ************************ WEBSITE START ***************


@ifhtml
@node index
@unnumbered LilyPond
@end ifhtml

@divId{pageHeader}
@heading LilyPond

... la notation musicale pour tous
@divEnd

@c @imageId{cmws,web-clef-g-eight-alpha.png,Catchy Musical Web Snippet}
@imageId{lilylogo,double-lily-modified3,png,LilyPond logo}
@c @im ageId{cmws,web-snippet-alpha.png,Catchy Musical Web Snippet}

@divId{quickSummary}
@c s u bheading Qu'est-ce que LilyPond ?

LilyPond est un logiciel de gravure musicale, destiné à produire
des partitions de qualité optimale.  Ce projet apporte à l'édition
musicale informatisée l'esthétique typographique de la gravure
traditionnelle.  LilyPond est un logiciel libre rattaché au
@uref{https://gnu.org,projet GNU}.

@divClass{align-right}
Plus sur LilyPond dans notre @ref{Introduction} !

@divEnd
@divEnd


@divId{homepage-main}

@divClass{column-center-top}

@subheading La beauté par l'exemple

@c This example image is the image from the website version of the essay
@c manual, downloaded to the pictures directory for use on the home page.
@c Large version is generated manually from ly file in pictures directory.
@divId{homepage-example-image-wrapper}
@imageClickable{bwv861-lilypond,png,,bwv861-lilypond-large,png,center}
@divEnd

@ifclear web_version
  @c no anchor links, just text

LilyPond est un outil à la fois puissant et flexible qui se charge de
graver toutes sortes de partitions, qu'il s'agisse de musique classique
(comme cet exemple de J.S. Bach), notation complexe, musique
ancienne, musique moderne, tablature, musique vocale, feuille de chant,
applications pédagogiques, grands projets, sortie personnalisée ainsi
que des diagrammes de Schenker.

@end ifclear
@ifset web_version
  @c anchor links, link to individual examples by their <a> tag

LilyPond est un outil à la fois puissant et flexible qui se charge de
graver toutes sortes de partitions, qu'il s'agisse de
@uref{examples.html#Musique-classique, musique classique}
(comme cet exemple de J.S. Bach),
@uref{examples.html#Notation-complexe, notation complexe},
@uref{examples.html#Musique-ancienne, musique ancienne},
@uref{examples.html#Musique-moderne, musique moderne},
@uref{examples.html#Tablature, tablature},
@uref{examples.html#Musique-vocale, musique vocale},
@uref{examples.html#Feuille-de-chant, feuille de chant},
@uref{examples.html#Applications-pedagogiques, applications pédagogiques},
@uref{examples.html#Grands-projets, grands projets},
@uref{examples.html#Sortie-personnalisee, sortie personnalisée},
ainsi que des
@uref{examples.html#Diagrammes-de-Schenker, diagrammes de Schenker}.

@end ifset

Venez puiser l'inspiration dans notre galerie
@ref{Exemples, d'exemples !}

@divEnd

@divClass{column-center-middle-color2}
@subheading Actualités

@c TODO: generate this automatically, including RSS feed.
@include en/web/news-headlines.itexi

@ref{Actualités, Actualités suivantes…}

@divEnd

@divEnd

@ifclear web_version
  @c do nothing
@end ifclear
@ifset web_version
  @c make the sidebar:
@divId{homepage-sidebar}

@subheading Branche stable

@c TODO: javascript to detect OS and suggest download?

@ref{Téléchargement, Téléchargemement de @versionStable}

@ref{Manuels, Manuels de @versionStable}

@subheading Branche de développement

@ref{Développement, Téléchargement de @versionDevel}

@ref{Développement, Manuels de @versionDevel}

@subheading Dépêches
@c VO Pondings
@divId{pondingsText}

@divEnd

@divEnd
@end ifset


@html

<script language="JavaScript" type="text/javascript">
  function loadXMLDoc(dname)
    {
      if (window.XMLHttpRequest)
        {
          xhttp=new XMLHttpRequest();
        }
      else
        {
          xhttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
      xhttp.open("GET",dname,false);
      xhttp.send();
      return xhttp.responseXML;
    }

  var xmlDoc = loadXMLDoc("tweets.xml");
  var tweets = xmlDoc.getElementsByTagName("tweet");
  var index = Math.floor(Math.random() * tweets.length);
  var tweet = tweets[index];
  var text = tweet.childNodes[0];
  document.getElementById("pondingsText").innerHTML = text.nodeValue;
</script>

@end html

@ifnottex

@divClass{hide}
@menu
* Introduction::        Comment créer des partitions
* Téléchargement::      Télécharger LilyPond
* Manuels::             Bibliothèque de LilyPond
* Communauté::          Comment contacter d'autres utilisateurs
@end menu
@divEnd

@end ifnottex

@contents

@iftex
@allowcodebreaks false
@end iftex

@c ****************** GENERAL STUFF FOR INFO ************
@ignore
Distributions will want to install lilypond.info in postinstall, doing:

    install-info --info-dir=/usr/share/info out[-www]/lilypond-web.info

  * Prepend GNU for dir, must be unique.

  * Do not list the `lilypond' node at toplevel, so that `info lilypond'
    goes to Top.

  * List all commands in direntry.

@end ignore

@c FIXME: this still doesn't solve the broken links in pdf and big
@c        html; we'll need a bunch of @iftext and stuff in here. -gp
@c ****************** SPECIAL MACROS FOR WEB MANUAL ************
@macro docLinks{name,base,refLink,split,big,pdf}
@subheading Lisez-le

@docLinksBare{\name\,\base\,\refLink\,\split\,\big\,\pdf\}

@end macro


@macro docLinkSplit{name,base,webLink}
  @docLink{\name\ (HTML multipages),\base\/index.html,\webLink\}
@end macro

@macro docLinkBig{name,base,webLink}
  @docLink{\name\ (HTML page unique),\base\-big-page.html,\webLink\}
@end macro

@macro docLinkPdf{name,base,webLink}
  @docLink{\base\.pdf,\base\.pdf,\webLink\}
@end macro


@macro docLinksBare{name,base,refLink,split,big,pdf}

@divClass{keep-bullets}
@itemize

@item @docLinkSplit{\name\,\base\,\split\} :
  manuel sous forme de plusieurs pages HTML
  @*@ @ @emph{-- chaque page est assez petite.}

@item @docLinkBig{\name\,\base\,\big\} :
  manuel sous forme d'une seule grande page
  @*@ @ @emph{@docSize{– un seul gros téléchargement, \base\-big-page.html, .}}

@item @docLinkPdf{\name\,\base\,\pdf\} :
  manuel au format PDF
  @*@ @ @emph{@docSize{– un seul gros téléchargement, \base\.pdf, .}}

@end itemize

@divEnd

@end macro


@c don't add any extra spaces in this macro -gp
@macro ifWebLinks{webLink,normalLink}
@ifclear web_version
  \normalLink\ :
@end ifclear
@ifset web_version
  \webLink\ :
@end ifset
@end macro


@ifhtml
@macro contactUsAbout{topic}

@divClass{heading-center}
@divClass{contactBox}
Si vous avez connaissance d'autres \topic\ qui mériteraient de figurer
ici, faites le nous savoir, en nous écrivant sur la liste bug-lilypond.
Si vous n'en êtes pas déjà membre, vous pouvez y souscrire à partir de
sa @uref{https://lists.gnu.org/mailman/listinfo/bug-lilypond,
page d'information}.

@divEnd
@divEnd

@end macro
@end ifhtml

@ifnothtml
@macro contactUsAbout{topic}
@cartouche
Si vous avez connaissance d'autres \topic\ qui mériteraient de figurer
ici, faites le nous savoir, en suivant les instructions de la rubrique
@ref{Signalement de bogue}.

@end cartouche

@end macro
@end ifnothtml

@include fr/web/introduction.itexi
@include fr/web/download.itexi
@include fr/web/manuals.itexi
@include fr/web/community.itexi

@bye
