# title	   makefile for stepmake

# subdir level:
#
depth = ..
#

# descent order into subdirectories:
#
SUBDIRS =
#

STEPMAKE_TEMPLATES=makedir


# bootstrap stepmake:
#
-include $(depth)/make/stepmake.make 
