# title	   makefile for stepmake

# subdir level:
#
depth = ..
#

# descent order into subdirectories:
#
SUBDIRS =
#

STEPMAKE_TEMPLATES=makedir install

# bootstrap stepmake:
#
-include $(depth)/make/stepmake.make 

INSTALLATION_DIR=$(datadir)/stepmake
INSTALLATION_FILES=GNUmakefile $(MAKE_FILES)

