LIB_PREFIX = lib
LIB_SUFFIX = .a

AR=ar

# LIBRARY = $(outdir)/$(LIB_PREFIX)$(NAME)$(LIB_SUFFIX)
LIBRARY = $(outdir)/$(LIB_PREFIX)rary$(LIB_SUFFIX)
INSTALL_LIBRARY = $(LIB_PREFIX)$(NAME)$(LIB_SUFFIX)
