\input texinfo @c -*-texinfo-*-
@documentencoding UTF-8
@documentlanguage en
@setfilename AUTHORS.info
@settitle AUTHORS - who did what for GNU LilyPond


@node Top
@top

@contents

@include en/macros.itexi
@include en/included/authors.itexi


This file lists authors of LilyPond, and what they wrote.  This list
is alphabetically ordered by surname.  This file lists people that have
contributed over 100 lines of code or the equivalent.


@subheading Current Development Team

@developersCurrent

@subheading Previous Development Team

@developersPrevious


@subheading Current Contributors

@subsubheading Programming

@coreCurrent

@subsubheading Font

@fontCurrent

@subsubheading Documentation

@docCurrent

@subsubheading Translation

@translationsCurrent


@subheading Past Contributors

@subsubheading Programming

@corePrevious

@subsubheading Font

@fontPrevious

@subsubheading Documentation

@docPrevious

@subsubheading Bug squad

@bugsquadPrevious

@subsubheading Support

@supportPrevious

@subsubheading Translation

@translationsPrevious


@bye
