\input texinfo @c -*-texinfo-*-
@documentencoding UTF-8
@documentlanguage en
@setfilename INSTALL.info
@settitle INSTALL - compiling and installing GNU LilyPond


@set INSTALL 1

@node Top
@top

@menu
* Compilation::
@end menu


@contents

@include en/macros.itexi

@node Compilation
@chapter Compilation

@include en/included/compile.itexi

@bye
