\input texinfo @c -*-texinfo-*-
@setfilename README.info
@settitle This is the toplevel README to LilyPond
@node Top, , , 
@top

@chapter This is the toplevel README to LilyPond


LilyPond is a music typesetter.  It produces beautiful sheet music
using a high level description file as input.  LilyPond is part of 
the GNU Project.

@section Versioning

LilyPond uses a versioning scheme similar to the Linux kernel.  In a
version "x.y.z", an even second number 'y' denotes a stable version.
For development versions 'y' is odd.

Version 1.4 is the latest stable release.


@section Compilation

For compiling and running LilyPond please refer to the installation
instructions.  These instructions can be found when you unpack lilypond,
as @file{lilypond-x.y.z/INSTALL.txt}.


NOTE: If you downloaded a binary (.rpm or a W95/NT .zip file),
you don't have to compile LilyPond.


@section Documentation

The documentation is available online at
@uref{http://www.lilypond.org/}.  You can also build it locally. This
does require a working LilyPond binary.  The following formats are
supported:
@itemize @bullet

@item HTML. Refer to INSTALL.txt for information
on how to make the HTML documentation.

@item @file{.dvi},  for the tutorial and reference manual. Do
@example 

 make -C Documentation/user/ dvi 

@end example 
The printable documentation is left in @file{Documentation/user/out/}.

@item paper. Create the .dvi documentation, and print it with dvips.

@end itemize


@section Comments

LilyPond is a long way from finished and polished, so please send your
criticism, comments, bugreports, patches, etc., to the mailing list,
@emph{not} to us personally.

We have the following mailing lists:

@itemize @bullet
@item @uref{http://mail.gnu.org/mailman/listinfo/info-gnu-music,info-gnu-music@@gnu.org}
is a low-volume list for information on the GNU Music project.
    This list is moderated; ask 
    @email{drl@@gnu.org, David R. Linn} or
    @email{hanwen@@cs.uu.nl, Han-Wen} to send announcements for this
list.
@item
@uref{http://mail.gnu.org/mailman/listinfo/gnu-music-discuss,gnu-music-discuss@@gnu.org}
  For general discussions concerning LilyPond.

@item @uref{http://mail.gnu.org/mailman/listinfo/help-gnu-music,help-gnu-music@@gnu.org}
    For help with using LilyPond.
@item @uref{http://mail.gnu.org/mailman/listinfo/bug-gnu-music,bug-gnu-music@@gnu.org}
If you have bugreports, you should send them to this list.
@end itemize


@section Windows 32

If you have received this file as part of a DOS/Window32 distribution
(@file{LilyPond-*.zip}), it is advisable to also download the
@uref{ftp://ftp.cs.uu.nl/pub/GNU/LilyPond/,source package}, since it
might contain more documentation

@section Caveats

If you have installed a previous version, be sure to remove old font
files, eg.,
@example 
rm `find /var/lib/texmf/fonts -name 'feta*'` 
@end example 

a script to do this for you is in @file{buildscripts/clean-fonts.sh}

@section Bugs

Send bug reports to @email{bug-gnu-music@@gnu.org}.  For help and
questions use @email{help-gnu-music@@gnu.org} and
@email{gnu-music-discuss@@gnu.org}.  Please consult the FAQ and
installation instructions before mailing your problems.



@bye
