\input texinfo @c -*-texinfo-*-
@setfilename README.info
@settitle Toplevel README

@html
<!--- @@WEB-TITLE@@=README --->
@end html

@node Top, , , 
@top

@chapter Toplevel README


LilyPond  is a music  typesetter.  It  produces beautiful  sheet music
using  a description  file as  input.   LilyPond  is  part of  the  GNU
Project.

@section Versioning

LilyPond uses a versioning scheme similar to the Linux kernel.  In a
version "x.y.z", an even second number 'y' denotes a stable version.
For development versions 'y' is odd.

Version 1.6 is the latest stable release.

@section Downloading

The primary download site for sourcecode is
@uref{ftp://ftp.cs.uu.nl/pub/GNU/LilyPond/}.

If you have a slow connection, then you are advised to use
@uref{ftp://ftp.xcf.berkeley.edu/pub/xdelta/,xdelta} for patching
source archives; Xdelta (@file{.xd}) files are supplied on the FTP site.

@section Compilation

For compiling and running LilyPond please refer to the installation
instructions.  These instructions can be found when you unpack
lilypond, as @file{lilypond-x.y.z/INSTALL.txt}. They are also
available on the web at
@uref{http://lilypond.org/Documentation/topdocs/out-www/INSTALL.html}.

NOTE: If you downloaded a binary (@file{.rpm} or use the Cygwin
@file{setup.exe} program, then you don't have to compile LilyPond.


@section Documentation

The documentation is available online at
@uref{http://www.lilypond.org/Documentation/out-www/index.html}.

You can also build it locally: follow the instructions under `Building
website' in the installation instructions.


@section Comments

LilyPond is a long way from finished so we appreciate your criticism,
comments, bugreports, patches, etc. Please send them to the mailing
list, not to us personally.

@html
<a name="mailing-lists">
@end html

We have the following mailing lists:

@itemize @bullet
@item @uref{http://mail.gnu.org/mailman/listinfo/info-lilypond,info-lilypond@@gnu.org}
is a low-volume list for information on the GNU Music project.
    This list is moderated; ask 
    @email{drl@@gnu.org, David R. Linn} or
    @email{hanwen@@cs.uu.nl, Han-Wen} to send announcements for this
list.

@item
@uref{http://mail.gnu.org/mailman/listinfo/lilypond-devel,lilypond-devel@@gnu.org}
  For discussions about developing lilypond, in particular the unstable series.

@item @uref{http://mail.gnu.org/mailman/listinfo/lilypond-user,lilypond-user@@gnu.org}
  For discussions about using lilypond, in particular the stable series.

@item @uref{http://mail.gnu.org/mailman/listinfo/bug-lilypond,bug-lilypond@@gnu.org}
If you have bugreports, you should send them to this list.

@item @uref{http://mail.gnu.org/mailman/listinfo/lilypond-cvs,lilypond-cvs@@gnu.org}
  Commit messages for CVS development. This is a high-volume moderated
  list.
@end itemize

You can search the lists from the following page:
@uref{http://lilypond.org/search, searching facilities}.

@section Caveats

If you have installed a previous version, be sure to remove old font
files, eg.,
@example 
rm `find /var/lib/texmf/fonts -name 'feta*'` 
@end example 
a script to do this for you is left
@file{buildscripts/out/clean-fonts}

@section Bugs

Send bug reports to @email{bug-lilypond@@gnu.org}.  For help and
questions use @email{lilypond-user@@gnu.org}.  Please consult the
documentation before mailing your problems.


@bye
