# -*-python-*-

import os

Import ('env')
telys = env['base_glob'] (env, '*.tely')
texis = env['base_glob'] (env, '*.texi') + map (env.TEXI, telys)

htmls = map (env.HTML, texis)
# map (env.HTML, ['AUTHORS.html',])
# map (env.HTML, ['AUTHORS.texi',])
env.Alias ('doc', htmls)

