depth = ..

NAME = kpath-guile
MODULE_NAME = kpath-guile

SCRIPTS = 
STEPMAKE_TEMPLATES = library c po

MODULE_CFLAGS = -std=c99
#MODULE_LDFLAGS = $(KPATHSEA_LIBS)

include $(depth)/make/stepmake.make 

$(outdir)/kpath.o: $(config_hh)


