ISOLANG = es
depth = ../..
SUBDIRS = learning notation texidocs usage web
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

UNSPLITTED_HTML_MANUALS = changes

EXTRA_DIST_FILES = web.texi search-box.ihtml

include $(depth)/make/stepmake.make
