ISOLANG = es
depth = ../..
SUBDIRS = learning notation texidocs usage
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

UNSPLITTED_HTML_MANUALS = changes

include $(depth)/make/stepmake.make
