ISOLANG = es
depth = ../..
SUBDIRS = essay learning notation texidocs usage web extending included
STEPMAKE_TEMPLATES = documentation texinfo
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root

include $(depth)/make/stepmake.make
