\input texinfo @c -*- coding: utf-8; mode: texinfo; -*-
@ignore
    Translation of GIT committish: 6c1cdaa331972442a8fd62d98da5adebfaa9a17b

    When revising a translation, copy the HEAD committish of the
    version that you are working on.  See TRANSLATION for details.
@end ignore

@setfilename web.info
@settitle LilyPond: notación musical para todos
@documentencoding UTF-8
@documentlanguage es
@afourpaper

@c `Web' was imported 2009-08-05 with git commit b938d71...
@c @macro copyrightDeclare
@c Copyright @copyright{} 2009 by the authors.
@c @end macro

@set FDL
@set web
@include macros.itexi

@c don't remove this comment.
@ignore
@omfcreator Graham Percival and Patrick McCarty
@omfdescription General info about the LilyPond music engraving system
@omftype program usage
@omfcategory Applications|Publishing
@omflanguage Spanish
@end ignore

@c Translators: Francisco Vila

@copying
Copyright @copyright{} 2009 por los autores.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1
or any later version published by the Free Software Foundation;
with no Invariant Sections.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.
@end quotation
@end copying


@c TITLE PAGE
@ifnottex
@node Arriba
@top LilyPond... notación musical para todos
@translationof Top
@end ifnottex


@c hack for texi2html, bleh -gp
@ifnothtml

@finalout

@titlepage
@title LilyPond
@subtitle El tipografiador de música
@titlefont{Información general}
@author El equipo de desarrollo de LilyPond

@vskip 0pt plus 1filll
@c @vskip 20pt

@insertcopying

Para LilyPond versión @version{}
@end titlepage
@end ifnothtml
@c end hack for texi2html


@c ************************ WEBSITE START ***************


@divId{pageHeader}
@heading LilyPond

... notación musical para todos
@divEnd

@c @imageId{cmws,web-clef-g-eight-alpha.png,Catchy Musical Web Snippet}
@imageId{lilylogo,double-lily-modified3,png,LilyPond logo}
@c @im ageId{cmws,web-snippet-alpha.png,Catchy Musical Web Snippet}

@divId{quickSummary}
@subheading ¿Qué es LilyPond?

LilyPond es un programa de grabado musical de código abierto,
consagrado a la producción de partituras de la calidad más alta
posible.  Este programa de software libre lleva la estética de la
música grabada de la forma tradicional a las partituras impresas
mediante ordenador.

@divClass{align-right}
¡Puede leer más en nuestra @ref{Introducción}!

@divEnd
@divEnd

@divClass{separator}
@divEnd


@divId{news}

@c TODO: generate this automatically, including RSS feed.
@include web/news-front.itexi

@divClass{float-right}
(@ref{Noticias antiguas})
@divEnd

@divEnd

@ifclear web_version
  @c do nothing
@end ifclear
@ifset web_version
  @c make the box:
@divId{latestVersion}
@subheading Enlaces rápidos

@c TODO: javascript to detect OS and suggest download?

@subsubheading Estable

@ref{Download, Descarga de @versionStable}

@ref{Manuals, Manuales de @versionStable}

@subsubheading Desarrollo

@ref{Development, Descarga de @versionDevel}

@ref{Development, Manuales de @versionDevel}

@divEnd


@ifnottex

@divClass{hide}
@menu
* Introducción::     Empiece aquí a crear partituras musicales.
* Descarga::         Obtener LilyPond.
* Manuales::         Léase los dichosos manuales (RTFM).
* Comunidad::        Póngase en contacto con otros usuarios.
@end menu
@divEnd

@end ifnottex

@contents

@c ****************** GENERAL STUFF FOR INFO ************
@ignore
Distributions will want to install lilypond.info in postinstall, doing:

    install-info --info-dir=/usr/share/info out[-www]/lilypond-web.info

  * Prepend GNU for dir, must be unique.

  * Do not list the `lilypond' node at toplevel, so that `info lilypond'
    goes to Top.

  * List all commands in direntry.

@c  * lilypond: (lilypond-application)Running LilyPond.      Invoking the
@c    LilyPond  program.
@end ignore

@c Info files are no longer installed in a subdirectory, images are
@c expected to be found in lilypond/ subdirectory.
@dircategory GNU LilyPond: el tipografiador de música
@direntry
* Manual de aprendizaje de LilyPond: (lilypond-learning).  Comience por aquí.
* Glosario musical: (music-glossary).                 Para usuarios de habla no inglesa.
* LilyPond: (lilypond-notation).                      Referencia de la notación con LilyPond.
* Fragmentos de código de LilyPond: (lilypond-snippets).         Consejos, trucos y ejemplos cortos.
* Referencia de funcionamiento interno: (lilypond-internals).  Definiciones para la construcción de trucos.
* Utilización del programa: (lilypond-application). Instalación y ejecución de las aplicaciones.
* Página web: (lilypond-general).    Vista previa de la nueva página.
* abc2ly: (lilypond-application)Invocación de abc2ly.      Importación de ABC.
* convert-ly: (lilypond-application)Actualización de archivos mediante convert-ly. Versiones antiguas de LilyPond.
* etf2ly: (lilypond-application)Invocar etf2ly.      Importación de Finale.
* lilypond-book: (lilypond-application)LilyPond-book. Intergrar texto y música.
* midi2ly: (lilypond-application)Invocar midi2ly.    Importación de MIDI.
* musicxml2ly: (lilypond-application)Invocar musicxml2ly.  Importación de MusicXML.
@end direntry


@c FIXME: this still doesn't solve the broken links in pdf and big
@c        html; we'll need a bunch of @iftext and stuff in here. -gp
@c ****************** SPECIAL MACROS FOR WEB MANUAL ************
@macro docLinks{name,base,refLink,split,big,bigsize,pdf,pdfsize}
@subheading Léalo

@itemize

@c normal case, special online case
@ifclear web_version
  @item \refLink\:
@end ifclear
@ifset web_version
  @c we assume that the online web version will be split html
  @item \split\:
@end ifset
lea el manual en el mismo formato que éste.

@end itemize

@subheading Todos los formatos

@divClass{keep-bullets}
@itemize

@ifclear web_version
  @item @uref{../\base\/index.html, \name\ (HTML seccionado)}:
@end ifclear
@ifset web_version
  @item \split\
@end ifset
  el manual está dividido en muchas páginas HTML.
  @*@ @ @emph{(una descarga pequeña por cada página)}

@ifclear web_version
  @item @uref{../\base\-big-page.html, \name\ (HTML monolítico)}:
@end ifclear
@ifset web_version
  @item \big\
@end ifset
  lea este manual como una sola página HTML enorme.
  @*@ @ @emph{(una sola descarga grande, \bigsize\)}

@ifclear web_version
  @item @uref{../\base\.pdf, \base\.pdf}:
@end ifclear
@ifset web_version
  @item \pdf\
@end ifset
  descárguelo como un archivo en formato PDF.
  @*@ @ @emph{(una sola descarga grande, \pdfsize\)}

@end itemize

@divEnd

@end macro

@c don't add any extra spaces in this macro -gp
@macro ifWebLinks{webLink,normalLink}
@ifclear web_version
  \normalLink\:
@end ifclear
@ifset web_version
  \webLink\:
@end ifset
@end macro

@include web/introduction.itexi
@include web/download.itexi
@include web/manuals.itexi
@include web/community.itexi

@bye
