# lib/Makefile

depth = ..

NAME = lily
SUBDIRS = include
# MODULE_LIBS= $(depth)/flower
MODULE_CXXFLAGS += -D_REENTRANT

include $(depth)/make/Stepmake.make 
include $(stepdir)/C++.make 
include $(stepdir)/Library.make 


