# title	   top level makefile for FlowerLib
# file	   flower/Makefile

# should reinstate versioning if shared libs are enabled.

depth = ..

NAME = ttftool
MODULE_NAME = ttftool
SUBDIRS = include 

SCRIPTS = 
README_FILES = README
EXTRA_DIST_FILES = $(README_FILES) $(SCRIPTS)
STEPMAKE_TEMPLATES = library c po

MODULE_CFLAGS = $(TTFTOOL_ENDIAN)

include $(depth)/make/stepmake.make 


