# -*-python-*-

Import ('env', 'src_glob')
sources = src_glob ('*.c')
includes = src_glob ('include/*.h')
outdir = Dir ('.').path

name = 'ttftool'
e = env.Copy ()
e.Append (CPPPATH = ['#/flower/include', '#/ttftool/include', outdir,])
if env['static']:
	e.Library (name, sources) 
if not env['static'] or env['shared']:
	e.SharedLibrary (name, sources)

po = env.Command ('lilypond.po', sources + includes, env['pocommand'])
env.Alias ('po-update', po)
