ISOLANG = nl
depth = ../..
SUBDIRS = general learning notation texidocs usage
STEPMAKE_TEMPLATES = documentation
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root
NO_PDF_FILES = 1

EXTRA_DIST_FILES = general.texi

include $(depth)/make/stepmake.make
