\input texinfo @c -*- coding: utf-8; mode: texinfo; documentlanguage: nl -*-
@c This file is part of web.texi
@ignore
    Translation of GIT committish: 1b3da70d81938d19a2b107382bbe25a267cf130b

    When revising a translation, copy the HEAD committish of the
    version that you are working on.  See TRANSLATION for details.
@end ignore


@setfilename web.info
@settitle LilyPond -- Muzieknotatie voor iedereen
@documentencoding UTF-8
@documentlanguage nl
@set web
@include macros.itexi
@afourpaper
@ifnottex
@node Top
@top
@translationof Top


@chapheading
@end ifnottex
@finalout
@titlepage
@title LilyPond
@subtitle
@titlefont{New Website}
@author Het LilyPond ontwikkelteam
@quotation
@end quotation
@vskip 20pt
@end titlepage
@copying
@quotation
@end quotation
@end copying
@divId{pageHeader}
@heading LilyPond

... muzieknotatie voor iedereen
@divEnd
@c @imageId{cmws,web-clef-g-eight-alpha.png,Catchy Musical Web Snippet}
@imageId{lilylogo,double-lily-modified3.png,LilyPond logo}
@c @im ageId{cmws,web-snippet-alpha.png,Catchy Musical Web Snippet}
@divId{quickSummary}
@subheading Wat is LilyPond?

LilyPond is een Open Source muziek-graveer programma, gewijd aan
het produceren van de hoogst mogelijke kwaliteit bladmuziek.

Wij brengen de esthetiek van traditioneel gegraveerde muziek naar
computer afdrukken.

LilyPond is Vrije Software, is gratis en is onderdeel van het
@uref{http://@/www@/.gnu@/.org/, GNU} project.

@divClass{align-right}
Lees de @ref{Inleiding}!

@c For this to work, essay needs to be split like we are
@c   --split=node --node-files
@c Dat en meer in ons @ressaynamed{Engraving, essay}.
@c Possibly, node Top always works?
@c Dat en meer in ons @ressaynamed{Top, essay}.
Dat en meer in ons @ref{automated-engraving,,Essay,essay,Essay}.

@divEnd
@divEnd
@divId{news}
@include news-front.itexi
@divClass{float-right}
@divEnd
@divEnd
@divId{latestVersion}
@subheading Quick links
@c TODO: javascript to detect OS and suggest download?
@subsubheading Stable
@ref{Download, Download 2.12.3}
@ref{Handleiding, Handleiding 2.12.3}
@subsubheading Unstable
@ref{Development, Download 2.13.2}
@ref{Handleiding, Handleiding 2.13.2}
@divEnd
@divClass{hide}
@menu
* inleiding::
* download::
* handleiding::
* community::
@end menu

@divEnd
@contents
@include web/introduction.itexi
@include web/download.itexi
@include web/manuals.itexi
@include web/community.itexi
@bye

