#!/bin/sh
#
# postinst script for the Debian GNU/Linux lilypond package
#
#   by Anthony Fok <foka@debian.org>
#   Initial release:  Sun, 26 Oct 1997 03:23:00 -0700
#     Last modified:  Wed, 22 Apr 1998 03:14:10 -0600

set -e

package=lilypond		# This is used for filenames!  Don't change it!
pkg_name="GNU LilyPond"

std_TEXMFMAIN=/usr/lib/texmf	# Debian's standard $TEXMFMAIN

TEXMFMAIN=`/usr/bin/kpsewhich -expand-var '$TEXMFMAIN'`
: ${TEXMFMAIN:=$std_TEXMFMAIN}

echo " Running /usr/bin/mktexlsr ..."
/usr/bin/mktexlsr

#DEBHELPER#

echo
echo " $pkg_name configuration completed."
echo " Please read /usr/doc/$package/README.Debian to get started."
