#!/bin/sh
#
# postinst script for the Debian GNU/Linux lilypond package
#   by Anthony Fok <foka@debian.org>
#   Initial release:  Sun, 26 Oct 1997 03:23:00 -0700
#     Last modified:  Thu, 26 Apr 2001 03:20:10 -0600

set -e

package=lilypond		# This is used for filenames!  Don't change it!
pkg_name="GNU LilyPond"

std_TEXMFMAIN=/usr/share/texmf	# Debian's standard $TEXMFMAIN

TEXMFMAIN=`/usr/bin/kpsewhich -expand-var '$TEXMFMAIN'`
: ${TEXMFMAIN:=$std_TEXMFMAIN}

echo " Running /usr/bin/mktexlsr $TEXMFMAIN..."
/usr/bin/mktexlsr $TEXMFMAIN

install-info --quiet \
	--section "Music" "Music" \
	--description='LilyPond, the GNU Project music typesetter' \
	/usr/share/info/lilypond.info.gz

#DEBHELPER#
echo
echo " $pkg_name configuration completed."
echo " Please read /usr/share/doc/lilypond/README.Debian to get started."
