#!/bin/sh
#
# postinst script for the Debian GNU/Linux lilypond package
#
#   by Anthony Fok <foka@debian.org>
#   Initial release:  Sun, 26 Oct 1997 03:23:00 -0700
#     Last modified:  Wed, 11 Nov 1998 22:59:49 -0700

set -e

package=lilypond		# This is used for filenames!  Don't change it!
pkg_name="GNU LilyPond"

std_TEXMFMAIN=/usr/lib/texmf	# Debian's standard $TEXMFMAIN

TEXMFMAIN=`/usr/bin/kpsewhich -expand-var '$TEXMFMAIN'`
: ${TEXMFMAIN:=$std_TEXMFMAIN}

echo " Running /usr/bin/mktexlsr ..."
/usr/bin/mktexlsr

#DEBHELPER#

# If we are the last package to use the old /usr/lib/texmf/doc,
# we will create the symlink to /usr/doc/texmf.  :-)
if rmdir /usr/lib/texmf/doc >/dev/null 2>&1
then
    ln -s /usr/doc/texmf /usr/lib/texmf/doc
fi

echo
echo " $pkg_name configuration completed."
echo " Please read /usr/doc/$package/README.Debian to get started."
