#!/bin/sh
#
# preinst script for the Debian GNU/Linux lilypond package
#   by Anthony Fok <foka@debian.org>
#   This is free software; see the GNU General Public Licence
#   version 2 or later for copying conditions.  There is NO warranty.
#   Last modified:  Mon,  5 Apr 1999 20:30:12 -0600

set -e

package=lilypond
font_supplier=public
font_typeface=lilypond
std_TEXMFMAIN=/usr/share/texmf
std_VARTEXFONTS=/var/spool/texmf

#DEBHELPER#

TEXMFMAIN=`/usr/bin/kpsewhich -expand-var '$TEXMFMAIN'`
: ${TEXMFMAIN:=$std_TEXMFMAIN}
VARTEXFONTS=`/usr/bin/kpsewhich -expand-var '$VARTEXFONTS'`
: ${VARTEXFONTS=$std_VARTEXFONTS}

LILYTEXINPUTS=$TEXMFMAIN/tex/$package
LILYMFINPUTS=$TEXMFMAIN/fonts/source/$font_supplier/$font_typeface

case "$1" in
    install|upgrade)
	# Clear out the old TFM and PK files in case the fonts were
	# left-over from previous installations
	rm -rf $VARTEXFONTS/tfm/$font_supplier/$font_typeface
	rm -rf $VARTEXFONTS/pk/*/$font_supplier/$font_typeface

	# Fix a silly bug in Debian's lilypond 1.0.17-1.  :-)
	if [ "$2" = "1.0.17-1" ]; then
	    rm -rf $VARTEXFONTS/tfm/$font_supplier/mf
	    rm -rf $VARTEXFONTS/pk/*/$font_supplier/mf
	fi
    ;;

    abort-upgrade)
    ;;

    *)
	echo "$0 called with unknown argument \`$1'" >&2
	exit 0
    ;;

esac
