# input/mutopia/J.S.Bach/GNUmakefile

depth = ../../..

SUBDIRS = Petites-Preludes 
EXTRA_DIST_FILES=

LOCALSTEPMAKE_TEMPLATES=ly mutopia
examples=wtk1-fugue2 baerenreiter-sarabande

include $(depth)/make/stepmake.make

