depth = ../../

STEPMAKE_TEMPLATES=documentation texinfo tex
LOCALSTEPMAKE_TEMPLATES=lilypond ly lysdoc
EXTRA_DIST_FILES=README

EXTRA_DIST_FILES+=expressive parts text

include $(depth)/make/stepmake.make

TITLE=Stuff waiting for LSR -- you should not see this!

