# file	   make/Makefile 

depth = ..
STEPMAKE_TEMPLATES=makedir
BLURBS=BLURB # COPERTINA FLAPTEKST

ifneq ($(strip $(state-vector)),)
EXTRA_DIST_FILES = STATE-VECTOR
endif

include $(depth)/make/stepmake.make 


