# ports/Makefile

depth = ..

SUBDIRS = mutopia

LOCALSTEPMAKE_TEMPLATES=mutopia

EXTRA_DIST_FILES = ports.make README.ports

# include $(depth)/make/stepmake.make 
include $(depth)/ports/ports.make

