depth = ../../

# NR 1
SUBDIRS = pitches rhythms expressive-marks repeats simultaneous-notes staff-notation editorial-and-educational-use text
# NR 2
SUBDIRS += vocal-music chords piano-music percussion guitar strings bagpipes ancient-notation


SUBDIRS += other


# old
SUBDIRS += parts spacing schemelanguage
SUBDIRS += real-music paper-and-layout


STEPMAKE_TEMPLATES=documentation
EXTRA_DIST_FILES=README

include $(depth)/make/stepmake.make

