%{
     English note names spelled out in full, and abbreviated
     with s for sharp and f for flat.
%}

\pitchnames #`(
	(cflatflat . ,(make-pitch -1 0 -2 ))
	(cflat . ,(make-pitch -1 0 -1 ))
	(c . ,(make-pitch -1 0 0 ))
	(csharp . ,(make-pitch -1 0 1 ))
	(csharpsharp . ,(make-pitch -1 0 2 ))
	(dflatflat . ,(make-pitch -1 1 -2 ))
	(dflat . ,(make-pitch -1 1 -1 ))
	(d . ,(make-pitch -1 1 0 ))
	(dsharp . ,(make-pitch -1 1 1 ))
	(dsharpsharp . ,(make-pitch -1 1 2 ))
	(eflatflat . ,(make-pitch -1 2 -2 ))
	(eflat . ,(make-pitch -1 2 -1 ))
	(e . ,(make-pitch -1 2 0 ))
	(esharp . ,(make-pitch -1 2 1 ))
	(esharpsharp . ,(make-pitch -1 2 2 ))
	(fflatflat . ,(make-pitch -1 3 -2 ))
	(fflat . ,(make-pitch -1 3 -1 ))
	(f . ,(make-pitch -1 3 0 ))
	(fsharp . ,(make-pitch -1 3 1 ))
	(fsharpsharp . ,(make-pitch -1 3 2 ))
	(gflatflat . ,(make-pitch -1 4 -2 ))
	(gflat . ,(make-pitch -1 4 -1 ))
	(g . ,(make-pitch -1 4 0 ))
	(gsharp . ,(make-pitch -1 4 1 ))
	(gsharpsharp . ,(make-pitch -1 4 2 ))
	(aflatflat . ,(make-pitch -1 5 -2 ))
	(aflat . ,(make-pitch -1 5 -1 ))
	(a . ,(make-pitch -1 5 0 ))
	(asharp . ,(make-pitch -1 5 1 ))
	(asharpsharp . ,(make-pitch -1 5 2 ))
	(bflatflat . ,(make-pitch -1 6 -2 ))
	(bflat . ,(make-pitch -1 6 -1 ))
	(b . ,(make-pitch -1 6 0 ))
	(bsharp . ,(make-pitch -1 6 1 ))
	(bsharpsharp . ,(make-pitch -1 6 2 ))

	(cff . ,(make-pitch -1 0 -2 ))
	(cf . ,(make-pitch -1 0 -1 ))
	(c . ,(make-pitch -1 0 0 ))
	(cs . ,(make-pitch -1 0 1 ))
	(css . ,(make-pitch -1 0 2 ))
	(dff . ,(make-pitch -1 1 -2 ))
	(df . ,(make-pitch -1 1 -1 ))
	(d . ,(make-pitch -1 1 0 ))
	(ds . ,(make-pitch -1 1 1 ))
	(dss . ,(make-pitch -1 1 2 ))
	(eff . ,(make-pitch -1 2 -2 ))
	(ef . ,(make-pitch -1 2 -1 ))
	(e . ,(make-pitch -1 2 0 ))

	(es . ,(make-pitch -1 2 1 ))    
	(ess . ,(make-pitch -1 2 2 ))
	(fff . ,(make-pitch -1 3 -2 ))
	(ff . ,(make-pitch -1 3 -1 ))
	(f . ,(make-pitch -1 3 0 ))
	(fs . ,(make-pitch -1 3 1 ))
	(fss . ,(make-pitch -1 3 2 ))
	(gff . ,(make-pitch -1 4 -2 ))
	(gf . ,(make-pitch -1 4 -1 ))
	(g . ,(make-pitch -1 4 0 ))
	(gs . ,(make-pitch -1 4 1 ))
	(gss . ,(make-pitch -1 4 2 ))
	(aff . ,(make-pitch -1 5 -2 ))
	(af . ,(make-pitch -1 5 -1 ))
	(a . ,(make-pitch -1 5 0 ))
	(as . ,(make-pitch -1 5 1 ))
	(ass . ,(make-pitch -1 5 2 ))
	(bff . ,(make-pitch -1 6 -2 ))
	(bf . ,(make-pitch -1 6 -1 ))
	(b . ,(make-pitch -1 6 0 ))
	(bs . ,(make-pitch -1 6 1 ))
	(bss . ,(make-pitch -1 6 2 ))
)

\version "1.5.68"

