%{
     English note names spelled out in full, and abbreviated
     with s for sharp and f for flat.
%}

pitchnamesEnglish = #`(
	(cflatflat . ,(ly:make-pitch -1 0 DOUBLE-FLAT))
	(cflat . ,(ly:make-pitch -1 0 FLAT))
	(c . ,(ly:make-pitch -1 0 NATURAL))
	(csharp . ,(ly:make-pitch -1 0 SHARP))
	(csharpsharp . ,(ly:make-pitch -1 0 DOUBLE-SHARP))
	(dflatflat . ,(ly:make-pitch -1 1 DOUBLE-FLAT))
	(dflat . ,(ly:make-pitch -1 1 FLAT))
	(d . ,(ly:make-pitch -1 1 NATURAL))
	(dsharp . ,(ly:make-pitch -1 1 SHARP))
	(dsharpsharp . ,(ly:make-pitch -1 1 DOUBLE-SHARP))
	(eflatflat . ,(ly:make-pitch -1 2 DOUBLE-FLAT))
	(eflat . ,(ly:make-pitch -1 2 FLAT))
	(e . ,(ly:make-pitch -1 2 NATURAL))
	(esharp . ,(ly:make-pitch -1 2 SHARP))
	(esharpsharp . ,(ly:make-pitch -1 2 DOUBLE-SHARP))
	(fflatflat . ,(ly:make-pitch -1 3 DOUBLE-FLAT))
	(fflat . ,(ly:make-pitch -1 3 FLAT))
	(f . ,(ly:make-pitch -1 3 NATURAL))
	(fsharp . ,(ly:make-pitch -1 3 SHARP))
	(fsharpsharp . ,(ly:make-pitch -1 3 DOUBLE-SHARP))
	(gflatflat . ,(ly:make-pitch -1 4 DOUBLE-FLAT))
	(gflat . ,(ly:make-pitch -1 4 FLAT))
	(g . ,(ly:make-pitch -1 4 NATURAL))
	(gsharp . ,(ly:make-pitch -1 4 SHARP))
	(gsharpsharp . ,(ly:make-pitch -1 4 DOUBLE-SHARP))
	(aflatflat . ,(ly:make-pitch -1 5 DOUBLE-FLAT))
	(aflat . ,(ly:make-pitch -1 5 FLAT))
	(a . ,(ly:make-pitch -1 5 NATURAL))
	(asharp . ,(ly:make-pitch -1 5 SHARP))
	(asharpsharp . ,(ly:make-pitch -1 5 DOUBLE-SHARP))
	(bflatflat . ,(ly:make-pitch -1 6 DOUBLE-FLAT))
	(bflat . ,(ly:make-pitch -1 6 FLAT))
	(b . ,(ly:make-pitch -1 6 NATURAL))
	(bsharp . ,(ly:make-pitch -1 6 SHARP))
	(bsharpsharp . ,(ly:make-pitch -1 6 DOUBLE-SHARP))

	(cff . ,(ly:make-pitch -1 0 DOUBLE-FLAT))
	(cf . ,(ly:make-pitch -1 0 FLAT))
	(c . ,(ly:make-pitch -1 0 NATURAL))
	(cs . ,(ly:make-pitch -1 0 SHARP))
	(css . ,(ly:make-pitch -1 0 DOUBLE-SHARP))
	(cx . ,(ly:make-pitch -1 0 DOUBLE-SHARP))
	(dff . ,(ly:make-pitch -1 1 DOUBLE-FLAT))
	(df . ,(ly:make-pitch -1 1 FLAT))
	(d . ,(ly:make-pitch -1 1 NATURAL))
	(ds . ,(ly:make-pitch -1 1 SHARP))
	(dss . ,(ly:make-pitch -1 1 DOUBLE-SHARP))
	(dx . ,(ly:make-pitch -1 1 DOUBLE-SHARP))
	(eff . ,(ly:make-pitch -1 2 DOUBLE-FLAT))
	(ef . ,(ly:make-pitch -1 2 FLAT))
	(e . ,(ly:make-pitch -1 2 NATURAL))

	(es . ,(ly:make-pitch -1 2 SHARP))    
	(ess . ,(ly:make-pitch -1 2 DOUBLE-SHARP))
	(ex . ,(ly:make-pitch -1 2 DOUBLE-SHARP))
	(fff . ,(ly:make-pitch -1 3 DOUBLE-FLAT))
	(ff . ,(ly:make-pitch -1 3 FLAT))
	(f . ,(ly:make-pitch -1 3 NATURAL))
	(fs . ,(ly:make-pitch -1 3 SHARP))
	(fss . ,(ly:make-pitch -1 3 DOUBLE-SHARP))
	(fx . ,(ly:make-pitch -1 3 DOUBLE-SHARP))
	(gff . ,(ly:make-pitch -1 4 DOUBLE-FLAT))
	(gf . ,(ly:make-pitch -1 4 FLAT))
	(g . ,(ly:make-pitch -1 4 NATURAL))
	(gs . ,(ly:make-pitch -1 4 SHARP))
	(gss . ,(ly:make-pitch -1 4 DOUBLE-SHARP))
	(gx . ,(ly:make-pitch -1 4 DOUBLE-SHARP))
	(aff . ,(ly:make-pitch -1 5 DOUBLE-FLAT))
	(af . ,(ly:make-pitch -1 5 FLAT))
	(a . ,(ly:make-pitch -1 5 NATURAL))
	(as . ,(ly:make-pitch -1 5 SHARP))
	(ass . ,(ly:make-pitch -1 5 DOUBLE-SHARP))
	(ax . ,(ly:make-pitch -1 5 DOUBLE-SHARP))
	(bff . ,(ly:make-pitch -1 6 DOUBLE-FLAT))
	(bf . ,(ly:make-pitch -1 6 FLAT))
	(b . ,(ly:make-pitch -1 6 NATURAL))
	(bs . ,(ly:make-pitch -1 6 SHARP))
	(bss . ,(ly:make-pitch -1 6 DOUBLE-SHARP))
	(bx . ,(ly:make-pitch -1 6 DOUBLE-SHARP))
)

pitchnames = \pitchnamesEnglish

\version "2.8.0"


#(ly:parser-set-note-names parser pitchnames)
