# -*-python-*-

import glob
import os

Import ('env')
here = os.getcwd ()
reldir = str (Dir ('.').srcnode ())
os.chdir (reldir)
sources = glob.glob ('*.ly')
os.chdir (here)
outdir = os.path.join (env['build'], reldir, env['out'])

lydir = os.path.join (env['sharedir_package_version'], 'ly')
env.Install (lydir, sources)
env.Alias ('install', lydir)
