\version "1.5.49"


dashHat= "marcato"
dashPlus= "stopped"
dashDash= "tenuto"
dashBar= "staccatissimo"
dashLarger= "accent"
dashDot= "staccato"


thumb = \script "thumb"
accent = \script "accent"
marcato = \script "marcato"
staccatissimo = \script "staccatissimo"
% Changed 27th October 2001 Heikki Junes <heikki.junes@hut.fi>
%  * portato = tenuto & staccato
%  * if you use portato = slur & staccato, then apply "c( d )e-."
portato = \script "portato"
fermata = \script "fermata"
stopped = \script "stopped"
staccato = \script "staccato"
tenuto = \script "tenuto"
upbow = \script "upbow"
downbow = \script "downbow"
lheel = \script "lheel"
rheel = \script "rheel"
ltoe = \script "ltoe"
rtoe = \script "rtoe"
turn = \script "turn"
open = \script "open"
flageolet = \script "flageolet"
reverseturn = \script "reverseturn"
trill = \script "trill"
prall = \script "prall"
mordent = \script "mordent"
prallprall = \script "prallprall"
prallmordent = \script "prallmordent"
upprall = \script "upprall"
downprall = \script "downprall"
segno = \script "segno"
coda = \script "coda"
