%
% common Swedish names for notes. "ess" means flat, "iss" means sharp
%
% by Mats Bengtsson.

\pitchnames #`(
	(cessess . ,(make-pitch -1 0 -2 ))
	(cess . ,(make-pitch -1 0 -1 ))
	(c . ,(make-pitch -1 0 0 ))
	(ciss . ,(make-pitch -1 0 1 ))
	(cississ . ,(make-pitch -1 0 2 ))
	(dessess . ,(make-pitch -1 1 -2 ))
	(dess . ,(make-pitch -1 1 -1 ))
	(d . ,(make-pitch -1 1 0 ))
	(diss . ,(make-pitch -1 1 1 ))
	(dississ . ,(make-pitch -1 1 2 ))
	(essess . ,(make-pitch -1 2 -2 ))
	(ess . ,(make-pitch -1 2 -1 ))
	(e . ,(make-pitch -1 2 0 ))
	(eiss . ,(make-pitch -1 2 1 ))
	(eississ . ,(make-pitch -1 2 2 ))
	(fessess . ,(make-pitch -1 3 -2 ))
	(fess . ,(make-pitch -1 3 -1 ))
	(f . ,(make-pitch -1 3 0 ))
	(fiss . ,(make-pitch -1 3 1 ))
	(fississ . ,(make-pitch -1 3 2 ))
	(gessess . ,(make-pitch -1 4 -2 ))
	(gess . ,(make-pitch -1 4 -1 ))
	(g . ,(make-pitch -1 4 0 ))
	(giss . ,(make-pitch -1 4 1 ))
	(gississ . ,(make-pitch -1 4 2 ))
	(assess . ,(make-pitch -1 5 -2 ))
	(ass . ,(make-pitch -1 5 -1 ))
	(a . ,(make-pitch -1 5 0 ))
	(aiss . ,(make-pitch -1 5 1 ))
	(aississ . ,(make-pitch -1 5 2 ))
	(hessess . ,(make-pitch -1 6 -2 ))
	(b . ,(make-pitch -1 6 -1 ))
	(h . ,(make-pitch -1 6 0 ))
	(hiss . ,(make-pitch -1 6 1 ))
	(hississ . ,(make-pitch -1 6 2 ))
)
\version "1.3.146"
