%
% common Swedish names for notes. "ess" means flat, "iss" means sharp
%
% by Mats Bengtsson.

\pitchnames #`(
	(cessess . ,(ly:make-pitch -1 0 -2 ))
	(cess . ,(ly:make-pitch -1 0 -1 ))
	(c . ,(ly:make-pitch -1 0 0 ))
	(ciss . ,(ly:make-pitch -1 0 1 ))
	(cississ . ,(ly:make-pitch -1 0 2 ))
	(dessess . ,(ly:make-pitch -1 1 -2 ))
	(dess . ,(ly:make-pitch -1 1 -1 ))
	(d . ,(ly:make-pitch -1 1 0 ))
	(diss . ,(ly:make-pitch -1 1 1 ))
	(dississ . ,(ly:make-pitch -1 1 2 ))
	(essess . ,(ly:make-pitch -1 2 -2 ))
	(ess . ,(ly:make-pitch -1 2 -1 ))
	(e . ,(ly:make-pitch -1 2 0 ))
	(eiss . ,(ly:make-pitch -1 2 1 ))
	(eississ . ,(ly:make-pitch -1 2 2 ))
	(fessess . ,(ly:make-pitch -1 3 -2 ))
	(fess . ,(ly:make-pitch -1 3 -1 ))
	(f . ,(ly:make-pitch -1 3 0 ))
	(fiss . ,(ly:make-pitch -1 3 1 ))
	(fississ . ,(ly:make-pitch -1 3 2 ))
	(gessess . ,(ly:make-pitch -1 4 -2 ))
	(gess . ,(ly:make-pitch -1 4 -1 ))
	(g . ,(ly:make-pitch -1 4 0 ))
	(giss . ,(ly:make-pitch -1 4 1 ))
	(gississ . ,(ly:make-pitch -1 4 2 ))
	(assess . ,(ly:make-pitch -1 5 -2 ))
	(ass . ,(ly:make-pitch -1 5 -1 ))
	(a . ,(ly:make-pitch -1 5 0 ))
	(aiss . ,(ly:make-pitch -1 5 1 ))
	(aississ . ,(ly:make-pitch -1 5 2 ))
	(hessess . ,(ly:make-pitch -1 6 -2 ))
	(b . ,(ly:make-pitch -1 6 -1 ))
	(h . ,(ly:make-pitch -1 6 0 ))
	(hiss . ,(ly:make-pitch -1 6 1 ))
	(hississ . ,(ly:make-pitch -1 6 2 ))
)
\version "1.7.3"
