# -*-python-*-

Import ('env', 'src_glob')
bib = src_glob ('*.bib')
env.AT_COPY ('index.html.in')

# todo: must make html-long.bst as source too.
#  make as source?

map (env.BIB2HTML, bib)
env.Alias ('doc', bib)

