FROM ubuntu:16.04 as build
RUN apt-get update && apt-get install --no-install-recommends -y \
        ca-certificates \
        wget \
    && true
# Download and extract urw-base35-fonts. Do this is in a build container to
# not distribute the whole archive, only the *.otf files.
# Do not use ADD which doesn't cache the downloaded archive. Once released, it
# will never change.
RUN wget -q https://github.com/ArtifexSoftware/urw-base35-fonts/archive/20170801.1.tar.gz \
    && mkdir -p /usr/share/fonts/otf/ && tar -C /usr/share/fonts/otf/ \
        -xf /20170801.1.tar.gz --strip-components=2 --wildcards '*/fonts/*.otf'


FROM ubuntu:16.04
COPY --from=build /usr/share/fonts/otf/ /usr/share/fonts/otf/
RUN apt-get update && apt-get --no-install-recommends install -y \
        autoconf \
        bison \
        flex \
        fontconfig \
        fontforge \
        fonts-texgyre \
        g++ \
        gettext \
        ghostscript \
        guile-1.8-dev \
        imagemagick \
        libfl-dev \
        libfontconfig1-dev \
        libfreetype6-dev \
        libglib2.0-dev \
        libgs-dev \
        libpango1.0-dev \
        make \
        netpbm \
        perl \
        pkg-config \
        python3 \
        rsync \
        texi2html \
        texinfo \
        texlive-binaries \
        texlive-fonts-recommended \
        texlive-generic-recommended \
        texlive-lang-cyrillic \
        texlive-metapost \
        zip \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc /usr/share/man

# Drop root user inside the container.
USER nobody
