depth = ../../..

STEPMAKE_TEMPLATES=documentation

EXTRA_DIST_FILES+=$(call src-wildcard,*.ly)
EXTRA_DIST_FILES+=$(call src-wildcard,*.ily)
EXTRA_DIST_FILES+=$(call src-wildcard,*.itexi)
EXTRA_DIST_FILES+=$(call src-wildcard,*.itely)

include $(depth)/make/stepmake.make
