# -*-python-*-

Import ('env', 'base_glob', 'install')
pos = base_glob ('*.po')
mos = map (env.MO, pos)

install (mos, env['localedir'])

env.Depends ('po', 'po-update')
# map (lambda x: env.Depends (x + '.mo', x + '.pom'), pos)
poms = map (env.POMERGE, pos)
env.Alias ('po-update', poms)
env.Alias ('po', mos)
#env.Alias ('all', mos)

