# -*-python-*-

Import ('env')
pos = env['glob'] (env, '*.po')
mos = map (env.MO, pos)
dir = env['localedir']
env.Install (dir, mos)
env.Alias ('install', dir)

env.Depends ('po', 'po-update')
# map (lambda x: env.Depends (x + '.mo', x + '.pom'), pos)
poms = map (env.POMERGE, pos)
env.Alias ('po-update', poms)
env.Alias ('po', mos)
#env.Alias ('all', mos)

