%% Do not edit this file; it is auto-generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.13.1"

\header {
  lsrtags = "simultaneous-notes"

%% Translation of GIT committish: 73115c93908af74c12a19753e79cbca47b2c2978
 doctitlees = "Voces adicionales para evitar colisiones"
 texidoces = "
En ciertos casos de polifonía compleja, se necesitan voces adicionales
para evitar colisiones entre las notas.  Las voces adicionales se
añaden definiendo una variable que utiliza la función de Scheme
context-spec-music.

"

%% Translation of GIT committish: 0364058d18eb91836302a567c18289209d6e9706
  texidocde = "
Ein einigen Fällen von sehr komplexer polyphoner Musik sind zusätzliche
Stimmen notwendig, um Zusammestöße zwischen den Noten zu vermeiden.
Wenn mehr als vier parallele Stimmen benötigt werden, können zusätzliche
Stimmen definiert werden, indem eine Variable mit der Funktion
@code{context-spec-music} definiert wird.

"
  doctitlede = "Zusätzliche Stimmen, um Zusammenstöße zu vermeiden"

  texidoc = "
In some instances of complex polyphonic music, additional voices are
necessary to prevent collisions between notes.  If more than four
parallel voices are needed, additional voices can be added by defining
a variable using the Scheme function @code{context-spec-music}.

"
  doctitle = "Additional voices to avoid collisions"
} % begin verbatim

voiceFive = #(context-spec-music (make-voice-props-set 4) 'Voice)
\relative c'' {
  \time 3/4 \key d \minor \partial 2
  <<
    { \voiceOne
      a4. a8
      e'4 e4. e8
      f4 d4. c8
    } \\ {
      \voiceThree
      f,2
      bes4 a2
      a4 s2
    } \\ {
      \voiceFive
      s2
      g4 g2
      f4 f2
    } \\ {
      \voiceTwo
      d2
      d4 cis2
      d4 bes2
    }
  >>
}
