%% Do not edit this file; it is auto-generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.11.38"

\header {
  lsrtags = "editorial-and-educational-use, chords, piano-music"
 texidoc = "
Fingerings for chords can be obtained by adding them to individual
pitches.
" }
% begin verbatim
\relative c'{
  < c-1 e-2 g-3 b-5 >2
  < d-1 f-2 a-3 c-5 >
}
