%% Do not edit this file; it is auto-generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.11.38"

\header {
  lsrtags = "rhythms, contexts-and-engravers"
 texidoc = "
The @code{measureLength} property, together with
@code{measurePosition}, determines when a barline is needed. However,
when using @code{\\compressMusic}, the scaling of durations makes it
difficult to change time signatures without making a mess of it.
Therefore, @code{measureLength} has to be set manually, using the
@code{ly:make-moment} callback. The second argument has to be the same
as the second argument of @code{\\compressMusic}. 
" }
% begin verbatim
\layout {
 \context { \Score
    \remove "Timing_translator"
    \remove "Default_bar_line_engraver"
 }
 \context {
   \Staff
   \consists "Timing_translator"
   \consists "Default_bar_line_engraver"
 }
}

<<
 \new Staff {
   \compressMusic #'(8 . 5) {
     \time 6/8
     \set Timing.measureLength = #(ly:make-moment 3 5)
     b8 b b b b b
     \time 2/4
     \set Timing.measureLength = #(ly:make-moment 2 5)
     b4 b
     }
   }
 \new Staff {
   \clef bass
   \time 2/4
   c2 d e f }   
 >>

