depth = ../../

SUBDIRS = ancient chords connecting contemporary education expressive
SUBDIRS += guitar parts pitch repeats spacing staff text vocal scheme other 

STEPMAKE_TEMPLATES=documentation texinfo tex
LOCALSTEPMAKE_TEMPLATES=lilypond ly lysdoc
EXTRA_DIST_FILES=README
include $(depth)/make/stepmake.make


TITLE=LilyPond Examples

