depth = ../../

SUBDIRS = ancient chords connecting contemporary

STEPMAKE_TEMPLATES=documentation texinfo tex
LOCALSTEPMAKE_TEMPLATES=lilypond ly lysdoc

include $(depth)/make/stepmake.make


TITLE=LilyPond Examples

