depth = ../../

# NR 1
SUBDIRS = pitches rhythms expressive repeats simultaneous staff editorial text


SUBDIRS += real-music

### FIXME: temporary template for creating other dirs.
###  will be removed once everything else is stable.
SUBDIRS += null

# old stuffs
SUBDIRS += ancient chords connecting contemporary education expressive
SUBDIRS += guitar parts repeats spacing staff text vocal scheme other 
SUBDIRS += engravers nonmusic instrument

STEPMAKE_TEMPLATES=documentation texinfo tex
LOCALSTEPMAKE_TEMPLATES=lilypond ly lysdoc
EXTRA_DIST_FILES=README
include $(depth)/make/stepmake.make


TITLE=LilyPond Examples

