%% Do not edit this file; it is auto-generated from LSR http://lsr.dsi.unimi.it
%% This file is in the public domain.
\version "2.12.0"

\header {
  lsrtags = "repeats"

  texidoces = "
También se pueden imprimir símbolos de porcentaje sueltos.  Esto se
hace introduciendo un silencio multicompás con una función de
impresión distinta:

"
  doctitlees = "Símbolos de porcentaje sueltos"

%% Translation of GIT committish :<0364058d18eb91836302a567c18289209d6e9706>
  texidocde = "
Isolierte Prozentwiederholungen können auch ausgegeben werden.  Das wird
erreicht, indem man eine Ganztaktpause notiert und ihre Ausgabeform
ändert:

"
  doctitlede = "Isolierte Prozentwiederholungen"

  texidoc = "
Isolated percents can also be printed.  This is done by entering a
multi-measure rest with a different print function:

"
  doctitle = "Isolated percent repeats"
} % begin verbatim

\relative c'' {
  \override MultiMeasureRest #'stencil
    = #ly:multi-measure-rest::percent
  \override MultiMeasureRest #'thickness = #0.48
  R1
}
