# -*-python-*-

Import ('env', 'install', 'src_glob')
py = src_glob ('*.py')
c = src_glob ('*.c')

cm = map (env.SharedObject, c)

py
cm

install (py, env['sharedir_package_version'] + '/python')
install (cm, env['libdir_package_version'] + '/python')
