# tex/Makefile

depth = ..


PS_FILES = $(wildcard *.ps)

EXTRA_DIST_FILES =  $(PS_FILES) 

INSTALLATION_DIR=$(datadir)/ps/
INSTALLATION_FILES=$(PS_FILES)

include $(depth)/make/stepmake.make
include $(stepdir)/installfiles.make

