depth = ..

PS_FILES = $(wildcard *.ps)

STEPMAKE_TEMPLATES=install
EXTRA_DIST_FILES = $(PS_FILES) 

INSTALLATION_DIR=$(local_lilypond_datadir)/ps/
INSTALLATION_FILES=$(PS_FILES)

include $(depth)/make/stepmake.make
