# -*-python-*-

Import ('env')
texdir = env['sharedir_package_version'] + '/tex'
psdir = env['sharedir_package_version'] + '/ps'
env.Install (psdir, ['lilyponddefs',])
env.Install (texdir, ['music-drawing-routines',])
#env.Alias ('install', texdir)
env.Alias ('install', psdir)
