# -*-python-*-

Import ('env')

dir = env['DESTDIR'] + env['sharedir_package_version'] + '/ps'
env.Install (dir, ['lilyponddefs.ps',])
env.Alias ('install', dir)

dir = env['DESTDIR'] + env['sharedir_package_version'] + '/tex'
env.Install (dir, ['music-drawing-routines.ps',])
env.Alias ('install', dir)
