# bin/Makefile

depth = ..

include $(depth)/make/Stepmake.make 


include $(stepdir)/Scripts.make

# want release, make-patch too!
SEXECUTABLES=convert-mudela mudela-book ly2dvi

include $(stepdir)/Executable.make


