# -*-python-*-

Import ('env')
sources = env['src_glob'] (env, '*.py')
gens = map (env.AT_COPY, sources)
dir = env['DESTDIR'] + env['bindir']
env.Install (dir, gens)
env.Alias ('install', env['bindir'])

po = env.Command ('lilypond.po', sources, env['pocommand'])
env.Alias ('po-update', po)
