# -*-python-*-

import os

Import ('env')
sources = env['src_glob'] (env, '*.py')
gen_files = map (lambda x: os.path.splitext (x)[0], sources)
gens = map (env.AT_COPY, sources)
dir = env['bindir']
env.Install (dir, gen_files)
