# -*-python-*-

Import ('env', 'install', 'src_glob')
sources = src_glob ('*.py')
scripts = map (env.AT_COPY, sources)

install (scripts, env['bindir'])

po = env.Command ('lilypond.po', sources, env['pocommand'])
env.Alias ('po-update', po)
