# file	   make/Makefile 

depth = ..
STEPMAKE_TEMPLATES=makedir install
##BLURBS=BLURB # COPERTINA FLAPTEKST

INSTALLATION_DIR=$(datadir)/make
INSTALLATION_FILES=$(DIST_FILES)

include $(depth)/make/stepmake.make 

