#!/bin/sh

echo '#ifndef FVERSION_HH'
echo '#define FVERSION_HH'

echo '#define FMAJORVERSION ' $1
echo '#define FMINORVERSION ' $2
echo '#define FPATCHLEVEL ' $3
echo '#define FVERSIONSTR "'$1.$2.$3'"'
echo '#define FCOMPILER "'$4'"'
echo '#endif'
