# -*-python-*-

Import ('env', 'src_glob')
sources = src_glob ('*.cc')
includes = src_glob ('*.hh')
outdir = Dir ('.').path

name = 'flower'
e = env.Copy ()
e.Append (CPPPATH = [outdir, 'include'])
if env['static']:
	e.Library (name, sources) 
if not env['static'] or env['shared']:
	e.SharedLibrary (name, sources)

po = env.Command ('lilypond.po', sources + includes, env['pocommand'])
env.Alias ('po-update', po)
