# -*-python-*-

Import ('env')
sources = env['src_glob'] (env, '*.cc')
outdir = Dir ('.').path

# abs_srcdir = Dir ('.').srcnode ().abspath
# abs_outdir = Dir ('.').abspath

name = 'flower'
e = env.Copy ()
e.Append (CPPPATH = [outdir, 'include'])
if env['static']:
	e.Library (name, sources) 
if not env['static'] or env['shared']:
	e.SharedLibrary (name, sources)
