depth = ../..

TEMPLATES = lilypond ly lysdoc 

COLLATED_FILES = AAA-intro-regression.tely $(sort $(LY_FILES))

include $(depth)/make/lilypond.make

TITLE=LilyPond Regression Tests
SUBDIRS := \
	abc2ly \
	include-path-modification \
	lilypond-book \
	midi \
	musicxml \
	other
