\version "2.21.0"

\header {
  texidoc = "@code{\\killCues} shall only remove real cue notes generated by
  @code{\\cueDuring}, but not other music quoted using @code{\\quoteDuring}."
}

mus = \relative { c'2 c c c c c c c }
\addQuote "M" \mus

quot = \relative { 
  d'2 \quoteDuring "M" { s1 } e2 \cueDuring "M" #UP { s1 } f2
}

\score { <<
  \quot
  \killCues \quot
>> }
