ISOLANG = zh
depth = ../..
# SUBDIRS = web learning notation texidocs usage included essay extending
SUBDIRS = web texidocs included
STEPMAKE_TEMPLATES = documentation texinfo
LOCALSTEPMAKE_TEMPLATES = lilypond ly doc-i18n-root
NO_PDF_FILES = 1

include $(depth)/make/stepmake.make
