\input texinfo @c -*- coding: utf-8; mode: texinfo; -*-

@settitle Suffix test for .texinfo


@node Suffix test for texinfo
@section Suffix test for @file{.texinfo}

Testing @code{lilypond-book} Texinfo mode with @file{.texinfo} file suffix.
@lilypond[fragment,relative=2]
\key c \minor c4 e d2
@end lilypond

@bye
