\input texinfo @c -*- coding: utf-8; mode: texinfo; -*-

@settitle Suffix test for .texi


@node Suffix test for texi
@section Suffix test for @file{.texi}

Testing @code{lilypond-book} Texinfo mode with @file{.texi} file suffix.
@lilypond[fragment,relative=2]
\key c \minor c4 e d2
@end lilypond

@bye
