# bin/Makefile

depth = ..
STEPMAKE_TEMPLATES=script install

include $(depth)/make/stepmake.make 

INSTALLATION_FILES=$(outdir)/gettext.py
INSTALLATION_DIR=$(datadir)/python

all: $(outdir)/gettext.py





