#!/bin/sh
# show-current.sh

. $LILYPOND_SOURCEDIR/VERSION 
VERSION=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_LEVEL
if [ "$MY_PATCH_LEVEL" != "" ]; then
  VERSION=$VERSION.$MY_PATCH_LEVEL
fi
echo $VERSION
