# mutopia/J.S.Bach/Makefile

depth = ../..

SUBDIRS = Petites-Preludes Solo-Cello-Suites Cembalo-Partitas
EXTRA_DIST_FILES=


LOCALSTEPMAKE_TEMPLATES=mutopia
examples=wtk1-fugue2

include $(depth)/make/stepmake.make

