# mutopia/J.S.Bach/GNUmakefile

depth = ../..

SUBDIRS = Petites-Preludes Cembalo-Partitas Duette
EXTRA_DIST_FILES=


LOCALSTEPMAKE_TEMPLATES=mutopia
examples=wtk1-fugue2

include $(depth)/make/stepmake.make

