# mutopia/J.S.Bach/Makefile

# subdir level:
#
depth = ../..
#

EXTRA_DISTFILES=preludes.tex
# descent order into subdirectories:
#
SUBDIRS = 
# 


# generic stuff/Makefile
#
include ./$(depth)/make/Mutopia.make
#

examples=scsii-menuetto wtk1-fugue2 preludes-2

include $(depth)/make/WWW.make
