# mutopia/j.s.bach/Makefile


# descent order into subdirectories:
#
SUBDIRS = 
# subdir level:
#
depth = ../..
#
# generic stuff/Makefile
#
include ./$(depth)/make/Include.make
#
#

# list of distribution files:
# 
LYFILES = $(wildcard *.ly)
TEXFILES = $(wildcard *.tex)
DISTFILES = Makefile $(LYFILES) $(TEXFILES) $(wildcard *.m4)
#

