depth=../..

EXTRA_DIST_FILES = $(call src-wildcard,*.sh) $(call src-wildcard,*.py)
EXTRA_DIST_FILES += pfx2ttf.fontforge
EXTRA_DIST_FILES += lily-git.tcl

include $(depth)/make/stepmake.make

default:
