# -*-python-*-

import glob
import os

## this only works for BuildDir aliasing, not for scons -Y ../scrdir
here = os.getcwd ()
os.chdir (str (Dir ('.').srcnode ()))
sources = glob.glob ('*.cc') + ['parser.yy', 'lexer.ll']
os.chdir (here)

name = 'lyparser'

Import ('env')
e = env.Copy ()

e.Append (YACCFLAGS = '-d')
e.Append (CPPPATH = ['include', '#/lily/include', '#/flower/include'])
e.Depends ('lexer.cc', 'parser.cc')

# some stuff here from lily-as-lib
if not os.path.exists ('main.cc'):
	if env['static']:
		e.Library (name, sources) 
	if not env['static'] or env['shared']:
		e.SharedLibrary (name, sources)
else:
	#e.Append (LIBS = ['lygui', 'lyparser', 'lily', 'flower'])
	e.Append (LIBS = ['flower'])
	e.ParseConfig ('guile-config link')
	name = 'lilypond-bin'
	e.Program (name, sources)
