
# subdir level:
#
depth = ../..
#

EXTRA_DISTFILES=

# descent order into subdirectories:
#
SUBDIRS = 
# 

# generic stuff/Makefile
#
include ./$(depth)/make/Mutopia.make
#

examples=cadenza

include $(depth)/make/WWW.make
