# This Brewfile lists all packages needed to build LilyPond binaries on macOS.

# Note that bison and flex are "keg-only" Homebrew formulae.  This means that
# you must set PATH, CPPFLAGS and LDFLAGS to make the build system, the compiler
# and the linker find bison and flex in the Homebrew installation instead of
# using the macOS system-provided ones (which are probably too old).  See "brew
# info bison" and "brew info flex".
brew "bison"
brew "flex"

brew "fontforge"
brew "meson"
brew "ninja"
brew "python"
brew "python-packaging"
brew "t1utils"
brew "texlive"
