#!/usr/bin/env python3

import argparse
import logging
import os
import sys

from lib import Config, all_dependencies

cpus = os.cpu_count() or 1

parser = argparse.ArgumentParser(description="Build dependencies")
parser.add_argument("--debug", help="show debugging messages", action="store_true")
parser.add_argument("--jobs", help="number of simultaneous jobs", default=cpus)
args = parser.parse_args()

# Show only INFO messages by default
if not args.debug:
    logging.basicConfig(format="%(message)s", level=logging.INFO)
else:
    logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.DEBUG)

c = Config(".", jobs=args.jobs)
c.create_directories()

logging.info("Downloading source code...")
for package in all_dependencies:
    package.download(c)

if not args.debug:
    # Print an empty line, so the output looks more natural.
    logging.info("")

for package in all_dependencies:
    logging.info("Building %s", package)
    if not package.prepare_sources(c):
        sys.exit(1)
    if not package.build(c):
        log_path = package.log_path(c)
        logging.info("See %s for more information", log_path)
        sys.exit(1)
