=head1 NAME

AUTHORS - who did what on GNU LilyPond?

=head1 DESCRIPTION

This file lists authors of GNU LilyPond, and what they wrote.  

=head1 AUTHORS

=over 4

=item *

Han-Wen Nienhuys <hanwen@stack.nl>, http://www.stack.nl/~hanwen

Main author, all files files except mentioned below

=item *

Jan Nieuwenhuizen <jan@digicash.com>, http://www.digicash.com/~jan

lily/midi-*, mi2mu/*, parts flower/string*.cc, make/*.make, */Makefile
parts of Documentation/mudela.pod, lib/*source-file*, lib/duration.cc,
lib/source*, flower/*{list,cursor}*, lily/rest-collision*,
lily/*abbreviation*, conflily, cygnus w32 stuff, lily/*perf*, some
input files

and corresponding header files.

=back

=head1 CONTRIBUTORS

=over 4

=item *

Mats Bengtsson <matsb@s3.kth.se>, parts of clef-reg.cc, clef-item.cc
swedish notenames, testing, general comments, duration
logs/longa/brevis etc

=item *

Werner Lemberg <xlwy01@uxp1.hrz.uni-dortmund.de>, misc bugfixes, some
Beam and Stem code. 

=item *

Alexandre Oliva <oliva@dcc.unicamp.br>, testing

=item *

Anthony Fok <foka@gpu.srv.ualberta.ca>, debian package: make/debian/*

=item *

Franc,ois Pinard <pinard@iro.umontreal.ca>, Neil Jerram
<nj104@cus.cam.ac.uk>. Documentation/Vocab*

=back

Your name could be here! If you want to help, then take a look at the
SMALLISH PROJECTS section of in the file F<TODO>. Some do not involve
coding C++

[And of course, J.S.Bach,  F.Schubert, T. Merula and W.A.Mozart]
