=head1 NAME

AUTHORS - who did what on GNU LilyPond?

=head1 DESCRIPTION

This file lists authors of GNU LilyPond, and what they wrote.  

=head1 AUTHORS

=over 4

=item * Han-Wen Nienhuys <hanwen@stack.nl>, http://www.stack.nl/~hanwen

Main author.

=item * Jan Nieuwenhuizen <jan@digicash.com>, http://www.digicash.com/~jan

Main author

=back

=head1 CONTRIBUTORS

=over 4

=item * Mats Bengtsson <matsb@s3.kth.se>,

parts of clef-reg.cc, clef-item.cc swedish notenames, testing, general
comments, duration logs/longa/brevis etc

=item * Jan Arne Fagertun <Jan.A.Fagertun@energy.sintef.no>,

TeX titling and lytodvi.sh

=item * Shay Rojanski

Some mudela source.

=item * Werner Lemberg <xlwy01@uxp1.hrz.uni-dortmund.de>,

misc bugfixes, some Beam and Stem code. 

=item * Donald Ervin Knuth, http://www.cs.stanford.edu/~?

mf/ital-*.mf (these were taken from the CM fonts)

=item * Alexandre Oliva <oliva@dcc.unicamp.br>, http://sunsite.unicamp.br/?

testing

=item * Anthony Fok <foka@debian.org>, 

debian package: debian/*

=item * Franc,ois Pinard <pinard@iro.umontreal.ca>, 

Documentation/Vocab*, internationalization stuff

=item *  Neil Jerram <nj104@cus.cam.ac.uk>. 

Documentation/Vocab*

=item * David R. Linn <drl@vuse.vanderbilt.edu>,

Mailing list maintenance.

=back

Your name could be here! If you want to help, then take a look at the
SMALLISH PROJECTS section of in the file F<TODO>. Some do not involve
coding C++

[And of course we sincerely thank J.S.Bach, F.Schubert, T. Merula and
W.A.Mozart for their beautiful music]
