\input texinfo @c -*-texinfo-*-
@setfilename disclaimer-w32.info
@settitle disclaimer-w32

@node Top, , , (dir)
@top


If you have the Cygnus gnu-windows32 port of the GNU utils, LilyPond
will work in Windows-NT (/95/98?).

We still recommend you use Unix.  In particular, use GNU/Linux: We've
been there, and we've seen it happen several times.  It is @emph{much}
easier and quicker to install RedHat Linux and LilyPond than to
obtain, compile and install all the necessary tools to compile and run
LilyPond on Windows.


@bye
