=head1 NAME

LilyError - LilyPond error messages

=head1 DESCRIPTION

This page documents error messages.

A correctly parsed F<input.ly> does not guarantuee output. A lot
(most) of the checking is done B<after> parsing (some checks even are
done after the break calc!); I'm sorry.

[yep.. has to be written..]
