=head1 NAME

LilyExamples - LilyPond example input

=head1 DESCRIPTION

This file documents the example inputfiles of LilyPond. Information of
each file: 

	title
	description (composer, piece)
	tested LilyPond features.
	copyright info

=head2 F<cadenza.ly>

A cadenza to Mozart Horn concerto no. 3. 

Features: cadenza mode.

Copyright: public domain

=head2 F<coriolan-alto.ly>

Ludwig van Beethoven (1770-1792), Opus 62 Ouverture zu Collins
Trauerspiel "Coriolan"

a 5 bar fragment of the alto part

Features: pushgroup, popgroup.

=head2 F<error.ly>

Error messages, context errors.

=head2 F<fugue1.midi.ly>


=head2 F<kortjakje.ly>

Ah, vous dirais-je, maman" (Mozart, KV 265), bare 
bones version.

Features: example with lots of newbie comment.

=head2 F<maartje.ly>

Features: partial measure.

=head2 F<martien.ly>, F<ml*.ly>

Martien Lohman, Viola Quartet. 

Features: n-plets, multi-staff scores.

Copyright:  copyright Martien Lohman 1997. 

=head2 F<midi.ly>

Features: midi output.

=head2 F<plet.ly>

Features: plets.

=head2 F<rhythm.ly>

Features: auto beams, multiple parralel meters.

=head2 F<scales.ly>

Features: plets, accents, beam steepnesses.

=head2 F<scsii-menuetto.ly>

J. S. Bach, Solo Cello Suites. Suite II part v Menuetto I

Features: breaking algorithm, chords, multivoice, accents

=head2 F<standchen.ly> 

St\"andchen (Serenade) "Leise flehen meine
Lieder" D.957 No.4 Franz Schubert (1797-1828)

Features: multivoice, accents, lyrics, chords, piano music

=head2 F<twinkle.ly>

Features: lyrics

=head2 F<wohltemperirt.ly>

JS Bach, Das Wohltemperirtes Clavier I, Fuga II (c-minor)

a 7 bar fragment. 

Features: stem direction, multivoice.

Copyright: public domain
