=head1 NAME

The Documentation of LilyPond -- the GNU Project music typesetter

=head1 DESCRIPTION

Note: These pages are created from the latest B<development snapshots>
of LilyPond.  You can look at the bottom if you want to know which
version this was.


=head2 Documentation: Introduction

=over 4

=item *
<! urg a href=ANNOUNCE-0.1$(DOTTEXT)>
<a href=ANNOUNCE-0.1
>
The announcement of 0.1
</a
>


=item *
<a href=DEDICATION
>
DEDICATION
</a
>

=item *
<a href=faq.html
>
FAQs
</a
>

=item *
<a href=INSTALL.html
>
The installation instructions.
</a
>

=back

=head2 Why: Background Information 

=over 4

=item *
<a href=MANIFESTO.html
>
Design criteria
</a
>

=item *
<a href=gnu-music.html
>
The GNU Music project
</a
>

=item *
<a href=mutopia.html
>
Mutopia -- Music To the People
</a
>

=item *
<a href=lelieblond.gif
>
The lilypond logo (Big, format: .gif)
</a
>

=item *
<a href=lelie_logo.gif
>
The lilypond logo (medium size, format: .gif)
</a
>


=back

=head2 Documentation: manuals


=over 4

=item *
<a href=../tex/out-www/index.html
>
TeX documents about LilyPond
</a
>

=item *
<a href=../man/out-www/index.html
>
Manual pages
</a
>

=back

=head2 The program

=over 5

=item *
<a href=TODO
>
The TODO list.
</a
>

=item *
<a href=NEWS
>
The Change log
</a
>

=item *
<a href=internals.html
>
internal structures.
</a
>

=item *
<a href=CodingStyle.html
>
The coding standards of the lilypond project.
</a
>

=item *
<a href=docxx/index.html
>
The DOC++ documentation of the C++ sources. [temporarily disabled]
</a
>

=item *
<a href=AUTHORS.html
>
AUTHORS
</a
>

=back

=head2 Links

=over 5

=item *
<a href=literature.html
>
Papers, books and online-resources on music typesetting
</a
>

=item *
<a href=other-packages.html
>
Other packages for printing music.
</a
>

=item *
<a href=links.html
>
B<download> LilyPond and other interesting links
</a
>



=back


