=head1 NAME

GNU LilyPond -- the Webpage

Excuse me for this poor page. I don't really have time for doing this..

=head1 DESCRIPTION

GNU LilyPond is a program to typeset music: it generates TeX (or
LaTeX) output from file input.

As a bonus, you can also output a MIDI file of what you typed.

<a href=example_output.html
>
examples of what LilyPond can do: MIDI, PS, .gif and input.
</a
>

=head1 DOCUMENTATION

=over 4


=item *
<a href=INSTALL.html
>
The installation instructions.
</a
>

=item *
<a href=MANIFESTO.html
>
Design criteria
</a
>

=item *
<a href=AUTHORS.html
>
AUTHORS
</a
>


=item *
<a href=lilypond.html
>
The manual page
</a
>

=item *
<a href=lilygut.html
>
internal structures.
</a
>

=item *
<a href=lilyliterature.html
>
Papers, books and online-resources on music typesetting
</a
>

=item *
<a href=other-packages.html
>
Other packages for printing music.
</a
>

=item *
<a href=mi2mu.html
>
manual page for mi2mu, the MIDI convertor.
</a
>

=item *
<a href=mudela.html
>
Mudela, the input format
</a
>

=item *
<a href=convert-mudela.html
>
The mudela convertor: convert-mudela
</a
>


=item *
<a href=faq.html
>
FAQs
</a
>

=item *
<a href=error.html
>
errors
</a
>

=item *
<a href=lelieblond.gif
>
The lilypond logo (Big, format: .gif)
</a
>

=item *
<a href=lelie_logo.gif
>
The lilypond logo (medium size, format: .gif)
</a
>


=item *
<a href=TODO.txt
>
The TODO list.
</a
>

=item *
<a href=NEWS.txt
>
The Change log
</a
>

=item *
<a href=CodingStyle.html
>
The coding standards of the lilypond project.
</a
>

=item *
<a href=gnu-music.html
>
The GNU Music project
</a
>

=item *
<a href=docxx/index.html
>
The DOC++ documentation of the C++ sources.
</a
>


=item *
Get it at ftp://pcnov095.win.tue.nl/pub/lilypond !


=item *
<a href=sconstat/stats.html
>
Stats on this page.
</a
>


=back


