\input texinfo @c -*-texinfo-*-
@setfilename index.info
@settitle index

@node Top, , , (dir)
@top




@unnumberedsec NAME
    

The Documentation of LilyPond -- the GNU Project music typesetter

@unnumberedsec DESCRIPTION
    

Note: These pages are created from the latest @strong{development snapshots}
of LilyPond.  You can look at the bottom if you want to know which
version this was.

@unnumberedsubsec Documentation: Introduction

@itemize @bullet
@item @uref{DEDICATION.html,DEDICATION}
@item @uref{faq.html,FAQs}
@item @uref{../topdocs/out-www/README.html,The README}
@item @uref{../topdocs/out-www/INSTALL.html,The installation instructions}
@end itemize

@unnumberedsubsec Why: Background Information

@itemize @bullet
@item  @uref{AIMS.html,Why?}
@item @uref{../pictures/out-www/lelieblond.png,The lilypond
  logo (Big, format: .png)}
@item @uref{../pictures/out-www/lelie_logo.png,The lilypond
  logo (medium size, format: .png)}
@end itemize

@unnumberedsubsec Documentation: manuals

@itemize @bullet
@item @uref{../tex/out-www/index.html,User documentation}
@item @uref{../metadoc/out-www/index.html,Hacker documentation}
@item @uref{../out-www/programs.html,`Manual pages'}
@item @uref{../bibliography/out-www/,Bibliography}
@item @uref{../tex/out-www/glossary.html,Musical vocabulary}
@end itemize

@unnumberedsubsec The program

@itemize @bullet
@item @uref{TODO.html,The TODO list}
@item @uref{NEWS.html,The Change log}
@item @uref{internals.html,About internal structures}
@item @uref{CodingStyle.html,The coding standards of the lilypond project}
@item @uref{../topdocs/out-www/AUTHORS.html,The Authors}
@item @uref{../topdocs/out-www/PATCHES.html,Sending and applying Patches}
@end itemize

@unnumberedsubsec Links

@itemize @bullet
@item @uref{../tex/out-www/index.html,Papers, books and online-resources on music typesetting}
@item @uref{../tex/out-www/index.html,Other packages for printing music}
@item @uref{links.html,bf(download) LilyPond and other interesting links}
@end itemize

@bye
