=head1 NAME

INSTALL - installing GNU LilyPond

=head1 DESCRIPTION

This page documents installation  and compilation of GNU LilyPond

=head1 PREREQUISITES

For compilation you need.

=over 5

=item *

A Unix system with GNU tools. GNU LilyPond is known to run on these
unices: Linux, AIX, Digital Unix and Solaris.

If you have the Cygnus WINDOWS32 port of the GNU utils, it will even
work in Windows NT/95, but don't promise to support it.

=item *

GNU C++ v2.7 or better, with libg++ installed.  Version 2.7.2
or better recommended. 

=item *

GNU make. 

=item *

Flex (2.5.1 or better). 

=item *

Bison. (Version 1.25 or better)

=back

=head1 RUNNING

GNU LilyPond does use a lot of resources. For operation you need the following:


=over 5

=item *

TeX

=item *

The MusixTeX fonts (I included those found in MusixTeX T.73). Beware,
the clef symbol seems to have changed its position in some versions,
(notably Egler's, a.k.a. OpusTeX). The MusixTeX fonts are included in
MusixTeX T.73, which can be had from any CTAN site, eg at

	ftp://ftp.shsu.edu/tex-archive/macros/musixtex/taupin
	ftp://ftp.tex.ac.uk/tex-archive/macros/musixtex/taupin
	ftp://ftp.dante.de/tex-archive/macros/musixtex/taupin

You only need the contents of the F<mf/> subdirectory of the package.

=head1 RECOMMENDED

Although not strictly necessary, these are recommended to have.

=over 5

=item *

Perl.  Most scripts are written in Perl. The documentation was created
with the perl's Plain Old Documentation.

=item *

(GNU) find


=item *

A fast computer (a full page of music typically takes 1 minute
on my 486/133, using the B<--enable-checking> compile. It's lot slower
than most MusiXTeX preprocessors)

=back


=head1 CONFIGURING and COMPILING

to install GNU LilyPond, simply type:

	configure
	make install

This will install the following files:

	/usr/local/man/man1/mi2mu.1
	/usr/local/man/man5/mudela.5
	/usr/local/man/man1/lilypond.1
	/usr/local/lib/libflower.{so,a}
	/usr/local/bin/lilypond
	/usr/local/bin/mi2mu
	/usr/local/share/lilypond/*
	/usr/lib/texmf/texmf/tex/lilypond/* 

The TeX include directory is detected dynamically, but it can be
adjusted with B<--enable-tex-prefix> and B<--enable-tex-dir>. The
above assumes that you are root and have the gnu development tools,
and your make is gnu make.  If this is not the case, you can adjust
your environment variables to your taste:

	export CPPFLAGS="-I /home/me/my_include -DWEIRD_FOOBAR" 
	configure

C<CPPFLAGS> are the preprocessor flags. 

the configure script is Cygnus configure, and it will accept
B<--help>. If you are not root, you will probably have to make it with

	configure --prefix=/home/me_myself_and_I/

In this case, you will have to set MFINPUTS, and TEXINPUTS accordingly.

If you want to install GNU LilyPond in F</usr/local>, and your TeX has
no default hooks for local stuff (mine is broken too), you can do:

	configure --prefix=/usr/local --enable-tex-prefix=/usr/lib/texmf

Since GNU LilyPond currently is beta, you are advised to also use

	--enable-debugging
	--enable-checking

other options include:

=over 4

=item --enable-shared

Make a shared library (gnu/linux, solaris (?) only ) 

=item 	--enable-printing

Enable debugging print routines (lilypond B<-d> option)

=item 	--enable-optimise

Set maximum optimisation

=item 	--enable-profiling

Compile with support for profiling

=item	--enable-tex-prefix

Set the directory where texmf lives

=item --enable-tex-dir

Set then directory tex input is in (detected as a subdir of tex-prefix)

=item --enable-mf-dir

Set then directory mf input is in (idem)

=back

All options are documented in the F<configure> help
The option B<--enable-optimise> is recommended for Real Life usage.

If you do

	make all

everything will be compiled, but nothing will be installed.  The
resulting binaries can be found in the subdirectories F<out/> (which
contain all files generated during compilation).


=head1 INSTALLING

If you have done a successful C<make>, then a simple

	make install

should do the trick. 

Install the musixtex fonts in a directory which TeX and MF knows (if
you are root, look for a directory which contains the directories with
AMS and CM source (*.mf) files. Create a subdir lilypond or musixtex
and copy the fonts into that). Do not forget to rehash TeX (if
applicable)

Example: my fonts are in F</usr/local/lib/texfonts/musixtex/>, and I
have a symlink pointing to that in
F</usr/lib/texmf/texmf/fonts/source/public/>. After I copied the
files, I ran "texhash"

ftp://hprib.lps.u-psud.fr/pub/music_zips/musixtex.zip

=head1 CAVEATS



=over 5

=item *

The -O2 option to gcc triggers a gcc bug on DEC Alpha in dstream.cc. You
should turn off this flag for this file.

=back

=head1 EXAMPLE

This is what I type in my xterm:

	lilypond someinput.ly
	tex lelie.tex
	xdvi test&

This is what the output looks like over here:

	hw:~/musix/spacer$ lilypond input/kortjakje.ly
	GNU LilyPond 0.0.71 #20/FlowerLib 1.1.20 #0
	Parsing ... [/home/hw/share/lilypond/init//symbol.ini  <..snip..>
	..	.ini]][input/kortjakje.ly]
	Creating elements ...
	Preprocessing elements... 
	Calculating column positions ... [3][8][13][17][21][25]
	Postprocessing elements...
	TeX output to lelie.tex ...

	hw:~/musix/spacer$ tex lelie
	This is TeX, Version 3.14159 (C version 6.1)
	(lelie.tex
	Hyphenation patterns for english, dutch, german, loaded.
	(/home/hw/lib/texmf/tex/lilypond/lilyponddefs.tex) [1] )
	Output written on lelie.dvi (1 page, 8944 bytes).
	Transcript written on lelie.log.

	hw:~/musix/spacer$ xdvi lelie&
	[1] 855

Check out the input files, some of them have comments
Please refer to the man page for more information.

=head1 REDHAT LINUX

RedHat Linux users should be able to get a RPM. A spec file is in
F<make/out/lilypond.spec>. You should be able to create an rpm as a normal
user. Be sure you have a ~/.rpmrc, and edit the RPM-dir in
F<Variables.make>. (If you create the RPM as a normal user the
permissions will not be set correctly, unfortunately)


=head1 WINDOZE

Windows NT:

you need the cygnus windows32 gnu port development stuff; have a look
at http://www.cygnus.com/gnu-win32.

to make GNU LilyPond under, brr, aargh, well, simply type:

	bash configure
	make windows32

=head1 AUTHORS

Han-Wen Nienhuys <hanwen@stack.nl>

Jan Nieuwenhuizen <jan@digicash.com>


Have fun!
