=head1 NAME

INSTALL - installing GNU LilyPond

=head1 DESCRIPTION

This page documents installation and compilation of GNU LilyPond

=head1 ABSTRACT

You do something which looks remotely like

	configure
	make
	make install

The detailed instructions follow here.

=head1 PREREQUISITES

For compilation you need.

=over 5

=item *

A GNU system: GNU LilyPond is known to run on these GNU systems: Linux
(PPC, intel), FreeBSD, AIX, NeXTStep, IRIX, Digital Unix and Solaris.

If you have the Cygnus WINDOWS32 port of the GNU utils, it will even
work in Windows NT/95, but we don't promise to support it.

=item *

GNU C++ version 2.7 or newer (yes, 2.8 is fine).

=item *

Python

=back

=head1 RUNNING

GNU LilyPond does use a lot of resources. For operation you need the following:

=over 5

=item *

TeX

=item *

A PostScript printer and/or viewer (such as Ghostscript) is strongly
recommended.  Xdvi will show all embedded PostScript too if you have
Ghostscript installed.

=back

=head1 RECOMMENDED

Although not strictly necessary, these are recommended to have.

=over 5

=item *

GNU make. 

=item *

Flex (version 2.5.4 or newer). 

=item *

Bison (version 1.25 or newer).

=item *

Perl-5.  Most documentation was created with the perl's Plain Old
Documentation. (I use 5.003)

=item *

Python.  Although perl is nice, python is better.  We will shift
towards python for build scripts

=item *

GNU find

=item *

A fast computer (a full page of music typically takes 1 minute on my
486/133, using the B<--enable-checking> compile. It's lot slower than
most MusiXTeX preprocessors)

=back

=head1 WEBSITE

If you want to auto-generate Lily's website, you'll need some additional
conversion tools.

=over 5

=item *

Xpmtoppm (from the libgr-progs package).

=item *

Bib2html (http://pertsserver.cs.uiuc.edu/~hull/bib2html.)
Which, in turn depends on Man2htlm (http://askdonald.ask.uni-karlsruhe.de/
hppd/hpux/Networking/WWW/Man2html-1.05) for proper installation (ugh).
TeTeX users, don't forget to rerun texhash.

=back

=head1 CONFIGURING and COMPILING

to install GNU LilyPond, simply type:

	configure
	make
	make install

This will install the following files:

	/usr/local/man/man1/mi2mu.1
	/usr/local/man/man1/convert-mudela.1
	/usr/local/man/man1/mudela-book.1
	/usr/local/man/man1/lilypond.1
	/usr/local/lib/libflower.{so,a}
	/usr/local/bin/lilypond
	/usr/local/bin/mi2mu
	/usr/local/share/lilypond/*
	/usr/lib/texmf/texmf/tex/lilypond/* 

The TeX include directory is detected dynamically, but it can be
adjusted with B<--enable-tex-prefix> and B<--enable-tex-dir>. The
above assumes that you are root and have the GNU development tools,
and your make is GNU make.  If this is not the case, you can adjust
your environment variables to your taste:

	export CPPFLAGS="-I /home/me/my_include -DWEIRD_FOOBAR" 
	configure

C<CPPFLAGS> are the preprocessor flags. 

the configure script is Cygnus configure, and it will accept
B<--help>. If you are not root, you will probably have to make it with

	configure --prefix=/home/me_myself_and_I/

In this case, you will have to set MFINPUTS, and TEXINPUTS accordingly.

If you want to install GNU LilyPond in F</usr/local>, and your TeX has
no default hooks for local stuff (mine is broken too), you can do:

	configure --prefix=/usr/local --enable-tex-prefix=/usr/lib/texmf

Since GNU LilyPond currently is beta, you are advised to also use

	--enable-debugging
	--enable-checking

other options include:

=over 4

=item B<--enable-shared>

Make a shared library (gnu/linux, solaris (?) only ) 

=item B<--enable-printing>

Enable debugging print routines (lilypond B<-d> option)

=item B<--enable-optimise>

Set maximum optimisation: compile with B<-O2>

=item B<--enable-profiling>

Compile with support for profiling

=item B<--enable-tex-prefix>

Set the directory where TeX and Metafont live

=item B<--enable-tex-dir>

Set then directory TeX input is in (detected as a subdir of
tex-prefix).  This should be a directory that is reachable both for
tex and latex.  On my system the best choice would be
F</usr/lib/texmf/texmf/tex/generic//>.

=item B<--enable-mf-dir>

Set the directory mf input is in (idem).   On my system the best
choice would be F</usr/lib/texmf/texmf/fonts/source/public/>.

=item B<--enable-config>

Output to different configuration files.  Needed for multi-platform
builds


=back

All options are documented in the F<configure> help
The option B<--enable-optimise> is recommended for Real Life usage.

If you do

	make all

everything will be compiled, but nothing will be installed.  The
resulting binaries can be found in the subdirectories F<out/> (which
contain all files generated during compilation).

=head1 CONFIGURING FOR MULTIPLE PLATFORMS

If you want to compile LilyPond with different configuration settings,
then, you can use the B<--enable-config> option.  Example: suppose I
want to build with and   without profiling.  Then I'd use the
following for the normal build, 

      configure --prefix=~ --disable-optimise --enable-checking
      make
      make install

and for the profiling version, I specify a different configuration.

      configure --prefix=~ --enable-profiling --enable-config=optprof --enable-optimise --disable-checking
      make configuration=optprof
      make configuration=optprof install


=head1 INSTALLING

If you have done a successful C<make>, then a simple

	make install

should do the trick.

If you are doing an upgrade, please remember to remove obsolete .pk
and .tfm files of the fonts.  A script has been provided to do the
work, see F<bin/clean-fonts.sh>.

=head1 CAVEATS

=over 5

=item *

The -O2 option to gcc triggers a gcc bug on DEC Alpha in dstream.cc. You
should turn off this flag for this file.

=item *

Perl5.003 and Perl5.004 use different syntax for pod2html.

=back

=head1 EXAMPLE

This is what I type in my xterm:

	lilypond someinput.ly
	tex someinput.tex
	xdvi someinput&

This is what the output looks like over here:

	GNU LilyPond 0.0.78 #4/FlowerLib 1.1.24 #0
	Parsing ... [/home/hw/share/lilypond/init//
		<..etc..>
		init//performer.ly]]][input/kortjakje.ly]
	Creating elements ...[8][16][24][25]
	Preprocessing elements... 
	Calculating column positions ... [14][25]
	Postprocessing elements...
	TeX output to someinput.tex ...
	Creating MIDI elements ...MIDI output to someinput.midi ...


	hw:~/musix/spacer$ xdvi someinput&
	[1] 855

Check out the input files, some of them have comments
Please refer to the man page for more information.

=head1 REDHAT LINUX

RedHat Linux users can compile an RPM. A spec file is in
F<make/out/lilypond.spec>.  You should install a gif file called
F<lelie_icon.gif> along with the sources.  You can generate this gif
file by typing

     make gifs

in the directory F<Documentation>.



=head1 DEBIAN GNU/LINUX

A Debian package is also available; contact Anthony Fok
<foka@debian.org>.  The build scripts are in the subdirectory debian/


=head1 WINDOWS NT/95

So, you're stuck with Windows, eh?  Well, don't worry, you just 
need (to get) Cygnus' windows32 port of gnu development stuff; 
have a look at http://www.cygnus.com/gnu-win32.

To make GNU LilyPond under, brr, aargh, shudder... windows32, well,
simply type:

	bash configure
	make

B<Note> If you rely on broken DOS/Windows tools such as pkzip/WinZIP 
to unpack the distribution, make sure the B<entire> source tree 
is unpacked correctly, in particular the empty out directories 
(F<flower/out>, F<lib/out> et. al.)

=head1 AUTHORS

Han-Wen Nienhuys <hanwen@cs.ruu.nl>

Jan Nieuwenhuizen <jan@digicash.com>


Have fun!
