\input texinfo @c -*-texinfo-*-
@setfilename links.info
@settitle links - Links to other related websites

@node Top, , , (dir)
@top

This page contains links to sites which may be of interest to LilyPond
users.

@unnumberedsubsec Music

@itemize @bullet
@item @uref{http://www.geocities.com/Vienna/Studio/1714/} and
@uref{http://johnsankey.webjump.com/} 
	John Sankey has taken up the task of recording classical
	music, and distributing the results at no cost.
@item @uref{http://sca.uwaterloo.ca/Mutopia/}
	Mutopia project (under construction).
@item @uref{http://www4.smart.net/~jcovey/scores/}
    Jeff Covey's guitar music.
@item @uref{http://www.pbm.com/~lindahl/ravenscroft/modern}
    Transcriptions of the music of Thomas Ravenscroft, partly using
    LilyPond
@end itemize

@unnumberedsubsec Software

@itemize @bullet
@item @uref{http://www.zib.de/Visual/software/doc++/index.html}
    A documentation system for C++ sources, which is used for the
    LilyPond sources.
@item @uref{ http://sound.condorow.net}
    Dave Philips' Linux sound applications page
@item @uref{http://www.home.fh-karlsruhe.de/~rost0001/web/musik/musik.html}
    Stochastic composing using LilyPond 
@end itemize

@unnumberedsubsec Philosophy

@itemize @bullet
@item @uref{http://www.gnu.org/}
    LilyPond is part of the GNU Project.  The GNU project is the name 
    of Richard Stallman's effort to create a freely available 
    system of software.
@item @uref{http://www.ram.org/ramblings/philosophy/fmp.html}
    Musings on free music, plus hints how to record your own (free) music.
@end itemize


@bye
