\input texinfo @c -*-texinfo-*-
@setfilename midi2ly.info
@settitle midi2ly

@node  midi2ly, , , Top
@menu
* midi2ly DESCRIPTION::           midi2ly DESCRIPTION
* midi2ly OPTIONS::               midi2ly OPTIONS
@end menu
@chapter midi2ly

@node  midi2ly DESCRIPTION, , , midi2ly
@section DESCRIPTION
midi2ly translates a MIDI input file to Mudela (GNU LilyPond source
format).  midi2ly is part of the GNU LilyPond music typesetting package.

	midi2ly [options] midi-file

@node  midi2ly OPTIONS, , , midi2ly
@section OPTIONS

@table @samp
@item -b, --no-quantify,
    Write exact durations, e.g.: `a4*385/384'.
@item -D, --debug,
    Print lots of debugging stuff.
@item -h, --help,
    Show a summary of usage.
@item -I, --include=@file{DIR},
    Add DIR to search path.
@item -k, --key=ACC[:MINOR],
    Set default key.  ACC > 0 sets number of sharps; ACC < 0 sets number 
    of flats.  A minor key is indicated by ":1".
@item -n, --no-silly,
    Assume no plets or double dots, assume smallest (reciprocal) duration 16.
@item -o, --output=@file{FILE},
    Set @file{FILE} as default output.
@item -p, --no-plets,
    Assume no plets.
@item -q, --quiet,
    Be quiet.
@item -s, --smallest=N,
    Assume no shorter (reciprocal) durations than N.
@item -v, --verbose,
    Be verbose.
@item -w, --warranty,
    Show the warranty with which midi2ly comes. (It comes with @strong{NO WARRANTY}!)
@item -x, --no-double-dots,
    Assume no double dotted notes.
@end table

@bye
