=head1 NAME

mudela-book - integrate LaTeX and mudela

=head1 SYNOPSIS

	mudela-book [options] [file]

=head1 DESCRIPTION

If no file is given, input is taken from the standard input

mudela-book runs LilyPond on fragments of mudela in your source file,
and produces a LaTeXable document, with formatted music.

	\begin{mudela}
	CONTENTS
	\end{mudela}

runs LilyPond on CONTENTS, and puts the result back, surrounded by
\preexample and \postexample commands. The \begin  takes  the
following options:

=over 4

=item fragment

mudela-book adds some redtape. You
can substitute voice-contents for CONTENTS in this case.

=item verbatim

CONTENTS is copied into the TeX source enclosed in a verbatim block.

=back

=head1 OPTIONS

=over 4

=item B<--outname>

The name of TeX file to output. If none is given, the output is
printed on stdout.

=item B<--outdir> 

The directory to output lilypond output and input to

=back

=head1 BUGS

Doesn't handle incorrect input sanely. 

=head1 AUTHOR

Han-Wen Nienhuys <hanwen@gnu.org>
