=head1 NAME 

Other-packages -- related packages 

=head1 DESCRIPTION 

A (not-at-all complete) overview of other music-typesetting/notation
packages. Feel free to add info (and mail it to me).  

=head2 Free packages (with source)

G Sharp, http://dept-info.labri.u-bordeaux.fr/~strandh/Gsharp

An alpha version notation editor for X. Source available on request.

Rosegarden, http://www.math.bath.ac.uk/~masjpf/rose.html

A Notation editor/Sequencer for X (win95 port underway). Outputs musictex.

Common Notation, ftp://ccrma-ftp.stanford.edu/pub/Lisp

A versatile lisp package. Part of the Common Music system. Input is in Lisp. 

Vivace, http://

A amateurish notation program for TclTk and X

MPP, http://www.stack.nl/~hanwen/mpp-english.html

A preprocessor to MusixTeX by Jan Nieuwenhuizen and Han-Wen Nienhuys.
It is outdated by its successor, LilyPond.

Music, http://

A TROFF preprocessor by Eric Foxley

MusicEase, ftp://ftp.secret.com/ad-ftp

Described in Computer vol 29(6)

MusE

A-R Music Engraving, by A-R Editions, Inc. Professional engraving on
Sun boxen.

Mup, http://www.arkkra.com/

A program which creates PS from a script input. Although it comes with
C source code, it is Shareware ($ 29).

PMX, http://www.gmd.de/Misc/Music/

A Preprocessor for MusiXTeX by Don Simons

Musi*TeX, http://www.gmd.de/Misc/Music/

MusixTeX is a macro package for TeX to typeset polyphonic or
instrumental music by Daniel Taupin, Ross Mitchell and Andreas
Egler. It includes a font set with lots symbols

ABC2MTeX, http://www.gmd.de/Misc/Music/

A preprocessor to MusixTeX by Chris Walshaw for way of transcribing folk
and traditional music. 

SceX

A preprocessor to MusixTeX by Miguel Filgueiras. Source in prolog
available on request. (?)

MUTEX, http://www.gmd.de/Misc/Music/

A TeX macro package for typesetting single-staff music by Angelika
Schofer & Andrea Steinbach. With some fonts


=head2 Free (zero cents)

Calliope, http://www.cl.cam.ac.uk/users/wfc/

A NeXT package by William F Clocksin. Requires Adobe fonts

=head2 Proprietary

LIME, http://datura.cerl.uiuc.edu/

Sibelius, http://www.acorn.co.uk/developers/sibelius

Finale

Score

Personal Composer

Mozart,

A shareware windows package, 

Capella

Encore

Musicator

=head2 Unknown

Berlioz, http://www.bsi.fr/~montel/

