=head1 NAME 

Other-packages -- related packages 

=head1 DESCRIPTION 

A (not-at-all complete) overview of other music-typesetting/notation
packages. Feel free to add info (and mail it to me).  

=head2 Free packages (with source)

=item G Sharp, http://dept-info.labri.u-bordeaux.fr/~strandh/Gsharp

An alpha version notation editor for X in Scheme. Source available on
request.

=item Rosegarden, http://www.math.bath.ac.uk/~masjpf/rose.html

A Notation editor/Sequencer for X (win95 port underway). Outputs musictex.

=item Common Notation,
http://www-ccrma.stanford.edu/CCRMA/Software/cmn/cmn.html

A versatile lisp package. Part of the Common Music system. Input is in
Lisp. It needs some Adobe fonts

=item Vivace, http://www.calband.berkeley.edu/~gmeeker/vivace

A amateurish notation program for TclTk and X.

=item MPP, http://www.stack.nl/~hanwen/mpp-english.html

A preprocessor to MusixTeX by Jan Nieuwenhuizen and Han-Wen Nienhuys.
It is outdated by its successor, LilyPond.

=item LilyPond, http://www.stack.nl/~hanwen/lilypond/index.html

Added for completeness. You are currently reading her documentation.

=item Music, http://www.cs.nott.ac.uk/Department/Staff/ef/printing.html

A TROFF preprocessor by Eric Foxley

=item PMX, http://www.gmd.de/Misc/Music/

A Preprocessor for MusiXTeX by Don Simons

=item Musi*TeX, http://www.gmd.de/Misc/Music/

MusixTeX is a macro package for TeX to typeset polyphonic or
instrumental music by Daniel Taupin, Ross Mitchell and Andreas
Egler. It includes a full-featured set of fonts.

=item ABC2MTeX, http://www.gmd.de/Misc/Music/

A preprocessor to MusixTeX by Chris Walshaw for transcribing folk and
traditional music.

=item SceX http://www.ncc.up.pt/~mig/SceX.html

A preprocessor to MusixTeX by Miguel Filgueiras. Source in prolog
available on request. (?)

=item MUTEX, http://www.gmd.de/Misc/Music/

A TeX macro package for typesetting single-staff music by Angelika
Schofer & Andrea Steinbach. With some fonts

=head2 Free (zero cents)

=item Calliope, http://www.cl.cam.ac.uk/users/wfc/

A NeXT package by William F. Clocksin. Requires Adobe fonts.

=head2 Proprietary

=item Scribe, http://

A formatter for medieval scores.

=item Mup, http://www.arkkra.com/

A program which creates PS from a script input. Although it comes with
C source code, it is Shareware.

=item MusicEase, http://mesa.colorado.edu/~grader/musicez.html 

Described in Computer vol 29(6). Shareware

=item LIME, http://datura.cerl.uiuc.edu/

Notation editor for W95 and Mac

=item Sibelius, http://www.acorn.co.uk/developers/sibelius

Notation/engraving on Acorn machines. 

=item Finale

=item Score

=item Personal Composer

=item MusE

A-R Music Engraving, by A-R Editions, Inc. Professional engraving on
Sun boxen.

=item Mozart, http://www.mozart.co.uk/

A shareware windows package  

=item Capella

=item Encore

=item Musicator

=head2 Unknown

=item MusiCopy, ? 

A project at Ohio State university, which was discontinued in 1987.

=item Berlioz, http://www.bsi.fr/~montel/

