;; (name . '((downindexstring . upindexstring)
;;           follow-into-staff :: bool
;;           dir-relative-to-stem :: int
;;           force-dir :: int
;;           priority :: int


(set! script-alist
      (append 
      '(("accDiscant" . ((accordion ("accDiscant"  . "accDiscant")) #f 0 1 0))
	("accDiscantF" . ((accordion ("accDiscantF" . "accDiscantF")) #f 0 1 0))
	("accDiscantE" . ((accordion ("accDiscantE" . "accDiscantE")) #f 0 1 0))
	("accDiscantEh" . ((accordion ("accDiscantEh" . "accDiscantEh")) #f 0 1 0))
	("accDiscantFE" . ((accordion ("accDiscantFE" . "accDiscantFE")) #f 0 1 0))
	("accDiscantFEh" . ((accordion ("accDiscantFEh" . "accDiscantFEh")) #f 0 1 0))
	("accDiscantEE" . ((accordion ("accDiscantEE" . "accDiscantEE")) #f 0 1 0))
	("accDiscantFEE" . ((accordion ("accDiscantFEE" . "accDiscantFEE")) #f 0 1 0))
	("accDiscantEEE" . ((accordion ("accDiscantEEE" . "accDiscantEEE")) #f 0 1 0))
	("accDiscantFEEE" . ((accordion ("accDiscantFEEE" . "accDiscantFEEE")) #f 0 1 0))
	("accDiscantS" . ((accordion ("accDiscantS" . "accDiscantS")) #f 0 1 0))
	("accDiscantFS" . ((accordion ("accDiscantFS" . "accDiscantFS")) #f 0 1 0))
	("accDiscantES" . ((accordion ("accDiscantES" . "accDiscantES")) #f 0 1 0))
	("accDiscantEhS" . ((accordion ("accDiscantEhS" . "accDiscantEhS")) #f 0 1 0))
	("accDiscantFES" . ((accordion ("accDiscantFES" . "accDiscantFES")) #f 0 1 0))
	("accDiscantFEhS" . ((accordion ("accDiscantFEhS" . "accDiscantFEhS")) #f 0 1 0))
	("accDiscantEES" . ((accordion ("accDiscantEES" . "accDiscantEES")) #f 0 1 0))
	("accDiscantFEES" . ((accordion ("accDiscantFEES" . "accDiscantFEES")) #f 0 1 0))
	("accDiscantEEES" . ((accordion ("accDiscantEEES" . "accDiscantEEES")) #f 0 1 0))
	("accDiscantFEEES" . ((accordion ("accDiscantFEEES" . "accDiscantFEEES")) #f 0 1 0))
	("accDiscantSS" . ((accordion ("accDiscantSS" . "accDiscantSS")) #f 0 1 0))
	("accDiscantESS" . ((accordion ("accDiscantESS" . "accDiscantESS")) #f 0 1 0))
	("accDiscantEESS" . ((accordion ("accDiscantEESS" . "accDiscantEESS")) #f 0 1 0))
	("accDiscantEEESS" . ((accordion ("accDiscantEEESS" . "accDiscantEEESS")) #f 0 1 0))
	("accFreebase" . ((accordion ("accFreebase" . "accFreebase")) #f 0 1 0))
	("accFreebaseF" . ((accordion ("accFreebaseF" . "accFreebaseF")) #f 0 1 0))
	("accFreebaseE" . ((accordion ("accFreebaseE" . "accFreebaseE")) #f 0 1 0))
	("accFreebaseFE" . ((accordion ("accFreebaseFE" . "accFreebaseFE")) #f 0 1 0))
	("accBayanbase" . ((accordion ("accBayanbase" . "accBayanbase")) #f 0 1 0))
	("accBayanbaseT" . ((accordion ("accBayanbaseT" . "accBayanbaseT")) #f 0 1 0))
	("accBayanbaseE" . ((accordion ("accBayanbaseE" . "accBayanbaseE")) #f 0 1 0))
	("accBayanbaseTE" . ((accordion ("accBayanbaseTE" . "accBayanbaseTE")) #f 0 1 0))
	("accBayanbaseEE" . ((accordion ("accBayanbaseEE" . "accBayanbaseEE")) #f 0 1 0))
	("accBayanbaseTEE" . ((accordion ("accBayanbaseTEE" . "accBayanbaseTEE")) #f 0 1 0))
	("accStdbase" . ((accordion ("accStdbase" . "accStdbase")) #f 0 1 0))
	("accStdbaseTp" . ((accordion ("accStdbaseTp" . "accStdbaseTp")) #f 0 1 0))
	("accStdbaseT" . ((accordion ("accStdbaseT" . "accStdbaseT")) #f 0 1 0))
	("accStdbaseBp" . ((accordion ("accStdbaseBp" . "accStdbaseBp")) #f 0 1 0))
	("accStdbaseM" . ((accordion ("accStdbaseM" . "accStdbaseM")) #f 0 1 0))
	("accSB" . ((accordion ("accSB" . "accSB")) #f 0 1 0))
	("accBB" . ((accordion ("accBB" . "accBB")) #f 0 1 0))
	("accOldEE" . ((accordion ("accOldEE" . "accOldEE")) #f 0 1 0))
	("accOldEES" . ((accordion ("accOldEES" . "accOldEES")) #f 0 1 0)))
      script-alist)
      )

