;; (name . '((downindexstring . upindexstring)
;;           follow-into-staff :: bool
;;           dir-relative-to-stem :: int
;;           force-dir :: int
;;           priority :: int


(set! script-alist
      (append 
      '(("accDiscant" . (("accDiscant"  . "accDiscant") #f 0 1 0))
	("accDiscantF" . (("accDiscantF" . "accDiscantF") #f 0 1 0))
	("accDiscantE" . (("accDiscantE" . "accDiscantE") #f 0 1 0))
	("accDiscantEh" . (("accDiscantEh" . "accDiscantEh") #f 0 1 0))
	("accDiscantFE" . (("accDiscantFE" . "accDiscantFE") #f 0 1 0))
	("accDiscantFEh" . (("accDiscantFEh" . "accDiscantFEh") #f 0 1 0))
	("accDiscantEE" . (("accDiscantEE" . "accDiscantEE") #f 0 1 0))
	("accDiscantFEE" . (("accDiscantFEE" . "accDiscantFEE") #f 0 1 0))
	("accDiscantEEE" . (("accDiscantEEE" . "accDiscantEEE") #f 0 1 0))
	("accDiscantFEEE" . (("accDiscantFEEE" . "accDiscantFEEE") #f 0 1 0))
	("accDiscantS" . (("accDiscantS" . "accDiscantS") #f 0 1 0))
	("accDiscantFS" . (("accDiscantFS" . "accDiscantFS") #f 0 1 0))
	("accDiscantES" . (("accDiscantES" . "accDiscantES") #f 0 1 0))
	("accDiscantEhS" . (("accDiscantEhS" . "accDiscantEhS") #f 0 1 0))
	("accDiscantFES" . (("accDiscantFES" . "accDiscantFES") #f 0 1 0))
	("accDiscantFEhS" . (("accDiscantFEhS" . "accDiscantFEhS") #f 0 1 0))
	("accDiscantEES" . (("accDiscantEES" . "accDiscantEES") #f 0 1 0))
	("accDiscantFEES" . (("accDiscantFEES" . "accDiscantFEES") #f 0 1 0))
	("accDiscantEEES" . (("accDiscantEEES" . "accDiscantEEES") #f 0 1 0))
	("accDiscantFEEES" . (("accDiscantFEEES" . "accDiscantFEEES") #f 0 1 0))
	("accDiscantSS" . (("accDiscantSS" . "accDiscantSS") #f 0 1 0))
	("accDiscantESS" . (("accDiscantESS" . "accDiscantESS") #f 0 1 0))
	("accDiscantEESS" . (("accDiscantEESS" . "accDiscantEESS") #f 0 1 0))
	("accDiscantEEESS" . (("accDiscantEEESS" . "accDiscantEEESS") #f 0 1 0))
	("accFreebase" . (("accFreebase" . "accFreebase") #f 0 1 0))
	("accFreebaseF" . (("accFreebaseF" . "accFreebaseF") #f 0 1 0))
	("accFreebaseE" . (("accFreebaseE" . "accFreebaseE") #f 0 1 0))
	("accFreebaseFE" . (("accFreebaseFE" . "accFreebaseFE") #f 0 1 0))
	("accBayanbase" . (("accBayanbase" . "accBayanbase") #f 0 1 0))
	("accBayanbaseT" . (("accBayanbaseT" . "accBayanbaseT") #f 0 1 0))
	("accBayanbaseE" . (("accBayanbaseE" . "accBayanbaseE") #f 0 1 0))
	("accBayanbaseTE" . (("accBayanbaseTE" . "accBayanbaseTE") #f 0 1 0))
	("accBayanbaseEE" . (("accBayanbaseEE" . "accBayanbaseEE") #f 0 1 0))
	("accBayanbaseTEE" . (("accBayanbaseTEE" . "accBayanbaseTEE") #f 0 1 0))
	("accStdbase" . (("accStdbase" . "accStdbase") #f 0 1 0))
	("accStdbaseTp" . (("accStdbaseTp" . "accStdbaseTp") #f 0 1 0))
	("accStdbaseT" . (("accStdbaseT" . "accStdbaseT") #f 0 1 0))
	("accStdbaseBp" . (("accStdbaseBp" . "accStdbaseBp") #f 0 1 0))
	("accStdbaseM" . (("accStdbaseM" . "accStdbaseM") #f 0 1 0))
	("accSB" . (("accSB" . "accSB") #f 0 1 0))
	("accBB" . (("accBB" . "accBB") #f 0 1 0))
	("accOldEE" . (("accOldEE" . "accOldEE") #f 0 1 0))
	("accOldEES" . (("accOldEES" . "accOldEES") #f 0 1 0)))
      script-alist)
      )
