# scm/Makefile

depth = ..

SCM_FILES = $(wildcard *.scm)
EXTRA_DIST_FILES = $(SCM_FILES)

INSTALLATION_DIR=$(datadir)/scm/
INSTALLATION_FILES=$(SCM_FILES)

STEPMAKE_TEMPLATES=install

include $(depth)/make/stepmake.make 

