# scm/Makefile

depth = ..

INSTALLATION_DIR=$(local_lilypond_datadir)/scm/
INSTALLATION_FILES=$(SCM_FILES)

XGETTEXT_FLAGS = --language=Lisp
STEPMAKE_TEMPLATES=install scm po

include $(depth)/make/stepmake.make

