depth = ../..

STEPMAKE_TEMPLATES=documentation

EXTRA_DIST_FILES= README
EXTRA_DIST_FILES+=$(call src-wildcard,*.ly)
EXTRA_DIST_FILES+=$(call src-wildcard,*.ily)
EXTRA_DIST_FILES+=$(call src-wildcard,lbook-*)

include $(depth)/make/stepmake.make
