\input texinfo @c -*-texinfo-*-
@setfilename lilbook.info
@settitle  lilypond-book test
@node Top, , ,
@top

@chapter lilypond-book test

@section Introduction

Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah
blah

Fragment:


@lilypond
\relative {
  c2 g'2^"test" \times 2/3 { f8 e d } c'2  g4
}
@end lilypond


Bla bla blah

This is a multipage / multipicture fragment:

@lilypond
\book {
  \score { { c1 \break \pageBreak c1 } }
}
@end lilypond

@bye
