# flower/lib/include/Makefile

# subdir level:
#
depth = ../..
#

# generic stuff/Makefile
#
include ./$(depth)/make/Include.make
include ./$(depth)/flower/.version

# identify module:
#
MODULE_NAME = flower

#

